src/util/resolve-dir.js
Mostly useful for existing Electron projects that want to migrate to Electron Forge.
=> fix(packager): throw error when electron-prebuilt-compile is not found

package.json, src/makers/darwin/dmg.js, src/makers/generic/zip.js, src/makers/linux/deb.js, src/makers/win32/squirrel.js, src/util/ensure-output.js, tmpl/package.json
There are two changes here:
* Create `ensure{Directory,File}` to `rimraf`+`mkdirp` the given output
* Add the debian maker
This is a PR mostly because my ES2015 code could use another pair of eyes.
=> Add support for electron-installer-debian

README.md
The most notable change is that I added a "requirements" column to the maker table. Trying to head off any issues being filed about `ENOENT $UTILITY_NAME` (I am sure they will be filed anyway - might have to do the same thing I do for missing `wine` in Electron Packager).
=> docs(generic): tweak the readme

ci/Dockerfile, package.json, src/electron-forge-package.js, src/electron-forge-start.js, src/util/install-dependencies.js, src/util/rebuild.js, test/cli_spec.js
Automatically rebuild modules when packaging and when starting.  We save on unnecessary rebuilds by persisting a file with the last rebuild arch in the build directory.
=> feat(packager): rebuild native modules automatically in all the right places

.appveyor.yml, README.md, src/electron-forge-lint.js, src/init/init-standard-fix.js, src/util/rebuild.js, test/cli_spec.js
Yes
N/A
N/A
N/A
Adds AppVeyor (Windows) as a CI service.
=> chore(tests): add AppVeyor support

src/util/rebuild.js
Yes
N/A
Not really, @malept do you know any native modules that are scoped.
Yes
Fix rebuilding scoped modules
=> fix(rebuilder): rebuild modules inside @ scoped folders as well

README.md, src/electron-forge-package.js, src/util/forge-config.js, test/fixture/dummy_app/package.json, test/fixture/dummy_js_conf/forge.config.js, test/fixture/dummy_js_conf/package.json, test/util_spec.js
Yes
Yes
Yes
Yes
Allow the `config.forge` prop in your package.json to point to a JS file that provides the config.
ISSUES CLOSED: #21
=> feat(generic): allow JS files to provide the config object

test/cli_spec.js
Yes
N/A
Yes
Yes
re-enable the help spec on macOS/Linux, since it works consistently there.
=> test(generic): only skip help spec on Windows

ci/Dockerfile
Yes
N/A
N/A
N/A
Needs to be here (instead of electron-forge-container) because the command causes Docker Hub's build workers to time out.
=> chore(tests): run flatpak runtime install in local Dockerfile

.cz.js, README.md, package.json, src/electron-forge-make.js, src/electron-forge-publish.js, src/electron-forge.js, src/makers/darwin/dmg.js, src/makers/generic/zip.js, src/makers/linux/deb.js, src/makers/linux/flatpak.js, src/makers/linux/rpm.js, src/makers/win32/squirrel.js, src/publishers/github.js, src/util/github.js, src/util/require-search.js, src/util/terminate.js, test/util_spec.js, tmpl/package.json
Adds the `electron-forge publish` command
* Adds a new forge config object `github_repository` so we know where to publish to
* All `makers` must now return an array of artifacts so that `publish` knows what to upload
* It creates a release if one does not already exist
An example of this working can be seen here.  I just want to get all three platforms publishing to GitHub through CI at the same time and then I'm super happy with this.
My playground app thing: https://github.com/MarshallOfSound/electron-forge-demo123/releases
/cc @malept
=> electron-forge publish

package.json, src/electron-forge-import.js, src/electron-forge-lint.js, src/electron-forge-make.js, src/electron-forge-package.js, src/electron-forge-publish.js, src/electron-forge-start.js, src/electron-forge.js, src/init/init-custom.js, src/init/init-directory.js, src/init/init-git.js, src/init/init-npm.js, src/init/init-standard-fix.js, src/init/init-starter-files.js, src/publishers/github.js, src/util/compile-hook.js, src/util/ora-handler.js, src/util/rebuild.js, src/util/resolve-dir.js, src/util/terminate.js
ISSUES CLOSED: #38
This looks quite large, but it is actually just indenting 😆
=> feat(generic): use an ora/promise helper instead of a global uncaughtRejection handler

.cz.js, package.json, src/electron-forge-install.js, src/electron-forge.js, src/installers/darwin/dmg.js, src/installers/darwin/zip.js, src/installers/linux/deb.js, src/installers/linux/rpm.js, src/util/linux-installer.js
This is a WIP for installing Electron apps from GitHub releases.  Currently tested / working / implemented on macOS and theoretically works on Windows (don't have a windows machine atm).
Need some help getting it working on linux (@malept)?
Example:
=> electron-forge install

src/electron-forge-init.js, src/init/init-npm.js, src/init/init-starter-files.js, tmpl/_compilerc
This PR switches the default Babel preset to use [babel-preset-env](https://github.com/babel/babel-preset-env) - this preset adjusts based on the current Electron version which Babel plugins to use. This PR also enables async/await and React by default, since these features are super common and don't have any overhead to enable if not in-use.
=> Use babel-preset-env in 'init'

tmpl/_eslintrc
See https://github.com/airbnb/javascript/pull/1224, https://github.com/sindresorhus/eslint-config-xo/pull/35, and https://github.com/eslint/eslint/pull/7823 for the sad details.
This doesn't completely solve the greater issue, but should at least help a little bit to ensure new Electron projects can be used on Windows
=> fix(starter): ensure linebreak-style is disabled

README.md, src/publishers/github.js
Adds support for two additional options on GitHub's release API, the ability to control whether the release is a pre-release, and also the ability to publish immediately rather than always use the draft option (current behavior).
- Are your changes appropriately documented?
**Yes, I have updated the README**
- Do your changes have sufficient test coverage? 
**No, but this file does not appear to have existing tests.  My guess is this would be too much overhead based upon needing to either (1) mock out github's api or (2) talk to the actual github api with a real repository.**
- Does the testsuite pass successfully on your local machine? 
**Yes, I also tested this manually by forking @MarshallOfSound's [demo repository here](https://github.com/stanlemon/electron-forge-demo123/releases)**
=> feat(publisher): add draft and prerelease options for publishing to github

package.json
The regression discussed [here](https://github.com/istanbuljs/babel-plugin-istanbul/issues/78) should now be addressed.
=> fix: regression in istanbul-lib-instrument around export const foo = () => {} now addressed

package.json, src/api/package.js
Yes
N/A
Yes
Yes
* Fixes a bug with detecting `asar.unpack`
* Upgrades Electron Packager to 8.5.0. Normally an upgrade is not particularly noteworthy, but this release deprecates the `version` option in favor of `electronVersion`, for clarity purposes.
=> Upgrade to Electron Packager 8.5.0

src/api/install.js, src/api/publish.js, src/installers/darwin/dmg.js, src/installers/darwin/zip.js, src/publishers/github.js, src/util/hdiutil.js, src/util/move-app.js
Yes
N/A
N/A (install logic not covered at all, big test PR incoming)
N/A
When installing a DMG file we now manually (and secretly) mount it, scan the mount point for `.app` files and then run the same logic on that .app file as the ones in ZIP folders.  This allows seamless no-user-interactive installs of apps packaged in ZIP files.
/cc @zeke
=> Install from dmg

src/api/package.js, src/init/init-custom.js, src/util/ora-handler.js, src/util/ora.js, src/util/terminate.js, test/slow/rebuild_spec_slow.js
ISSUES CLOSED: #100
Yes
N/A
N/A
Yes
Remove the `ora.ora` patch and instead use an ora util
=> refactor(generic): move ora.ora to an ora helper for ease of submodule use

src/api/make.js
Check the 'name' property of electronPackagerConfig to determine the out path
ISSUES CLOSED: #102
Yes
N/A
N/A
Yes
See above
=> fix(maker): detect out path of package step correctly

.gitignore, src/api/start.js, test/slow/start_spec_slow.js
**Have you read the [section in CONTRIBUTING.md about pull requests](https://github.com/electron-userland/electron-forge/blob/master/CONTRIBUTING.md#filing-pull-requests)?** Yes
**Are your changes appropriately documented?** Yes
**Do your changes have sufficient test coverage?** I'd like to add a test to confirm a successful run resolves with the spawned handle in `start_spec_slow.js`, but haven't yet grokked the test setup. Advice very much appreciated if this is blocking :)
**Does the testsuite pass successfully on your local machine?** Yes
**Summarize your changes:** Resolve `start` API usage with a handle to the spawned process
=> Resolve `start` API usage with a handle to the spawned process

src/api/import.js, src/api/install.js, src/api/make.js, src/publishers/github.js, src/util/messages.js
Fixes #111 
Fixes #112
Fixes #114
Fixes #108
Yes
Yes
N/A
Yes
Fix the things 😆 
Pretty straight forward
* Wrap all console logs in interactive checks
* Remove `process.exit` calls 'cos that's just plain wrong
* Provide a config option to the `import` API for `updateScripts`
* Default `electronVersion` to `@latest`
=> Ember fixes

README.md, tmpl/package.json
Yes
Um, yes 😄 
N/A
N/A
Adds an example for the GitHub publish target, and also adds `github_repository.name` to the default `package.json`. I've seen two questions about this in the Atom #electron room separately, so I figured the docs needed updating 😄
=> Publish to GitHub docs

src/api/import.js
Yes
Yes
I believe so?
Yes
- Consuming `api#import` w/ an undefined `electronName` was throwing. This change checks for its existence before trying to resolve (& rm) its path
- Consuming `api#import` w/ `{ updateScripts: false }` was preventing deps removal and permitting script updates. This change reverses these behaviours
- Consuming `api#import` would install `electron-compile` & `electron-prebuilt-compile` as deps vs. devDeps. …
=> Fix bugs w/ import scripts

issue_template.md, pull_request_template.md
* <del>The changes have sufficient test coverage</del> (not applicable).
* <del>The testsuite passes successfully on my local machine</del> (not applicable).
* Fixes a formatting typo in the issue template
* Add checkboxes and user-visible preambles to both templates
* The preamble in the issue template encourages template-specific issues to be filed in the templates repo
Similar changes in the Packager issue template hasn't produced any changes in issue reporter behavior, but one can hope :pray:
=> GitHub template enhancements

.appveyor.yml
=> fix(ci): Use the preinstalled yarn on AppVeyor

src/api/start.js, src/electron-forge-start.js, test/fast/electron_forge_start_spec.js, test/fast/start_spec.js
The start command allows the caller to specify the directory for the Electron forge project, and then assumes that its main module is the Electron application. However, some projects may contain multiple Electron applications, or may want to specify an html file or a URL as the Electron application (see [here](https://github.com/electron/electron/blob/cf694ef32b78f0904219c6c8ba554d3d5cbea037/default_app/main.js#L338)).
So, this adds an optional 'appPath' API option (and corresponding '-p'/'--app-path' CLI option) that is the path to the Electron application relative to the electron forge project (the 'dir' option).
This also fixes the start command-line options parsing, which was passing all arguments through to the Electron application instead of parsing out …
=> feat(generic): Support setting the Electron app path in start()

src/api/start.js, src/electron-forge-start.js, test/fast/electron_forge_start_spec.js, test/fast/start_spec.js
=> feat(starter): automatically wipe the ELECTRON_RUN_AS_NODE variable unless specified

src/makers/win32/appx.js, src/makers/win32/squirrel.js, test/slow/api_spec_slow.js
ISSUES CLOSED: #119
Yes
Yes (arguably the docs did not match the code)
Yes
Yes
Allow users to override most of the default electron-windows-store config set by Forge.
Fixes #119.
@felixrieseberg are there any of the default params aside from `inputDirectory` and `outputDirectory` that we do not want the user to override? FOr instance, perhaps `packageExecutable`?
=> fix(maker): allow most appx default config to be overridden by the user

src/publishers/github.js
This PR fixes #156. The `node-github` client made a recent change where all responses return a `meta` and `data` field instead of just returning the `data`: https://github.com/mikedeboer/node-github/commit/ceeefb2c478ca4302e1fe60dece10bc40075eaaf
This was causing errors in the github publisher, using the updated API solved the problem.
=> use updated node-github response API for github publisher

src/api/make.js, src/api/publish.js
Change `make` and `publish` command to search `node_modules` folder relative to app directory even when `electron-forge` is installed globally.
Fixes #175
=> Search local node modules folder for maker / publisher

package.json
The electron-installer-redhat package was recently updated with some improvements including:
* Better handling of `package.json` `author` string
* Hyphen characters (`-`) in version string now automatiacally converted to dots (`.`) in RPM version field since they are not allowed there
Updated `package.json` to use `^0.4.0` instead of `^0.3.0` for the `electron-installer-redhat` package.
=> Upgrade `electron-installer-redhat` to v0.4.0

src/init/init-npm.js, test/slow/api_spec_slow.js, tmpl/_compilerc
=> fix(initializer): set electron version to be float in init step

package.json
* cross-env: [4.0.0](https://github.com/kentcdodds/cross-env/releases/tag/v4.0.0)
* ~electron-installer-flatpack: 0.5.0 (0.6.0 is not yet released on NPM, see: https://github.com/endlessm/electron-installer-flatpak/issues/11)~ _test is broken and I want to release for `ember-electron`_
* electron-windows-store: 0.10.1 (https://github.com/felixrieseberg/electron-windows-store/pull/69)
* Sinon: [2.1.0](http://sinonjs.org/releases/v2.0.0/migrating-to-2.0/)
* sudo-prompt: [7.0.0](https://github.com/jorangreef/sudo-prompt/commit/810e87f9baef220702d268b2b76573533c795127)
=> chore(generic): update various dependencies

README.md, package.json, script/vscode.cmd, script/vscode.sh, src/electron-forge-start.js, test/fast/start_spec.js
Currently only on Darwin and Linux, win32 implementation to come
Basically adds a new binary to target with VS Code that mangles the args so we can pass node debug args through node without them making the forge host process enter debugging mode. 😆
=> feat(starter): provide an executable to start forge in a vscode debugger compatible way

src/api/make.js, src/api/package.js, src/api/start.js, src/makers/darwin/dmg.js, src/util/hook.js, test/fast/hook_spec.js, test/fast/start_spec.js
This adds super basic hooks in the codebase, they are noops if the hook doesn't exist.  Documentation for these hooks will go up on the site after this PR is merged.
Fixes #197
=> Hooks :tada:

src/makers/darwin/dmg.js, src/makers/generic/zip.js, src/makers/win32/squirrel.js
This makes all makers include the version in their artifact output, breaking change, should be included the the make platform breaking change bump
=> [BREAKING CHANGE] Ensure all assets outputted by make are versioned

README.md, package.json, src/api/publish.js, src/publishers/electron-release-server.js, test/fast/install-dependencies_spec.js, test/fast/publish_spec.js
This adds a new publish target for the widely used https://github.com/ArekSredzki/electron-release-server
Creates the version and uploads all assets, only config required is username, password and base URL.  If you don't want to put username/password in your forge config you can set them through environment variables.  See https://electronforge.io/config/extra/secure
=> Electron Release Server Publisher

script/vscode.cmd, script/vscode.sh, src/electron-forge-start.js, test/fast/electron_forge_start_spec.js, test/fast/start_spec.js
=> [BREAKING] refactor(starter): use double dash instead of triple dash to pass args through

src/api/start.js, src/electron-forge-start.js, test/fast/electron_forge_start_spec.js, test/fast/start_spec.js
I’m working on a project that runs specs when launched with a command-line flag (eg `electron-forge start --- --test`). I like doing it that way because the tests run in exactly the same env as the app, but electron-forge isn’t returning the exit code from `app.exit(1)`.
This PR alters the `start.js` API so that if the Electron child process exits with a non-zero status code, forge exits with the same code (similar to `lint.js`). The existing tests still pass and I've written an additional one for the exit code scenario.
=> fix(start): exit forge with same status code as Electron if nonzero

package.json, src/api/import.js, src/api/install.js, src/api/make.js, src/api/package.js, src/electron-forge-make.js, src/electron-forge-package.js, src/electron-forge-publish.js, src/electron-forge-start.js, src/init/init-custom.js, src/init/init-directory.js, src/init/init-git.js, src/init/init-npm.js, src/init/init-starter-files.js, src/installers/darwin/dmg.js, src/installers/darwin/zip.js, src/makers/win32/squirrel.js, src/publishers/electron-release-server.js, src/util/compile-hook.js, src/util/config.js, src/util/ensure-output.js, src/util/forge-config.js, src/util/move-app.js, src/util/read-package-json.js, src/util/resolve-dir.js, test/fast/config_spec.js, test/fast/ensure-output_spec.js, test/slow/api_spec_slow.js, test/slow/rebuild_spec_slow.js
As of `fs-extra` 3.0.0, it comes with builtin Promise support, so a wrapper module is no longer necessary.
Also comes with a non-deprecated `fs.exists` method.
This was pretty much a search/replace, so it wouldn't surprise me if I screwed up somewhere.
=> refactor(generic): replace fs-promise with fs-extra

src/electron-forge.js
ISSUES CLOSED: #215
This fixes the `--` not working issue by overriding the `executeSubCommand` function on our commander instance to map any args found (anything after `--`) to be after `--` again when spawning the sub command.
=> fix(starter): fix double dash arg pass through

package.json, src/util/linux-installer.js
* ~~The changes have sufficient test coverage~~ (not applicable).
* ~~The testsuite passes successfully on my local machine~~ (not applicable).
Not worth using a branch of a Node module just for Promise support for one platform.
I manually tested the "sudo succeeds" path and the "sudo fails" path via `electron-forge install MarshallOfSound/electron-forge-demo123` and selecting the Debian package.
Closes #58.
=> refactor(installer): replace electron-sudo with sudo-prompt

package.json, test/slow/install_spec_slow.js
I was looking at `chai-fetch-mock` because I was wondering what it did (since it's one of two dependencies preventing us from upgrading `chai`), and it doesn't look like we're using any of its features. `fetch-mock` is still required for tests. @MarshallOfSound let me know if we're going to be using any of its features (now or soon) and I'll close this PR.
=> chore(tests): remove unnecessary chai-fetch-mock dependency

src/api/package.js, src/util/ora.js
Packager oras still used to show up because we weren't (and can't) use `asyncOra`, instead we know just toggle between `fakeOra` and `ora` manually 👍
=> fix(packager): make packager respect the interactive flag and silence its oras

src/init/init-starter-files.js
We use the excellent fs-extra module now :smile:
Also, I try to avoid `forEach` unless there's a good reason to use it. Especially given that Node 6 is required.
=> refactor(initializer): use fs.copy and for...of

src/api/start.js, src/electron-forge-start.js, test/fast/electron_forge_start_spec.js, test/fast/start_spec.js
Adds a new `--inspect-electron` arg to start to launch electron in inspect mode 😄
=> feat(starter): add easy way to inspect electron main process from forge

src/api/start.js, test/fast/start_spec.js
Start the `electron-prebuilt-compile` binary from the module folder so we don't have to rely on npm/yarn to install into the .bin folder correctly
Helps #269
=> fix(starter): start electron-prebuilt-compile binary from its module folder

README.md
* ~~The changes have sufficient test coverage~~ (not applicable).
* ~~The testsuite passes successfully on my local machine~~ (not applicable).
Fixes #109.
=> docs(packager): list the Packager options that are not configurable

tabtab-install.js
* ~~The changes have sufficient test coverage~~ (not applicable).
When you install Forge via something like `npm install electron-forge --save-dev` (i.e., not globally), this warning shows up:
https://travis-ci.org/malept/electron-forge-demo123/jobs/265829065#L524-L535
This is because tabtab is a peer dependency when Forge is installed locally. To fix this, I just called the CLI as a `require()` instead of via `spawn-rx`.
=> fix(generic): fix installing tab completion when installing Forge locally

src/electron-forge.js, src/util/check-system.js, test/fast/system_spec.js
* Add yarn 0.27.5 to the whitelist, but only for darwin/linux platforms
* Add a newline to the package manager warning for readability
* Integrate the package manager warning into `ora` so the output isn't messed up with the interactive spinner
=> Check package manager tweaks

README.md, src/api/publish.js, src/electron-forge-publish.js, test/fast/publish_spec.js
Rename `target` option in the publish API to `publishTargets`, and only allow the param to be an Array of Strings, per the FIXMEs.
Also updated the docs to mention that multiple targets are allowed.
=> BREAKING CHANGE: Replace deprecated publish option

src/api/make.js, src/api/publish.js, src/electron-forge-publish.js, src/publishers/github.js, src/util/publish-state.js, test/fast/publish_spec.js, test/slow/api_spec_slow.js
to allow post-make publishes
Fixes #230
Looking at the tests best explains what this does, basically you can run `publish --dry-run` and it will make distributables **but not actually upload them**.  It will instead serialize into JSON the information required to upload them including platform, arch, configs and such and save those in a standard location relative to the out directory.
Then when you resume a dry run forge will scan for all saved dry runs and restore them skipping the make step completely and relying on the saved serialized information.
This allows you to make on all three platforms and then at a later point download those artifacts to one deployment machine and deploy everything in one go.
It actually looks kinda similar to a cool thing …
=> feat(publisher): adds dryRun and resumeDryRun to the API

src/api/lint.js, src/init/init-npm.js
Add the flag directly to the NPM script call for the `airbnb` linter.
ISSUES CLOSED: electron-userland/electron-forge-templates#48
=> fix(linter): don't pass --color to linters that don't support it

src/init/init-npm.js, tmpl/index.js
This is something I suggested in the Slack channel a while ago and only recently remembered it.
=> feat(initializer): add electron-squirrel-startup to the default template

src/util/forge-config.js, test/fast/forge-config_spec.js
* ~~[ ] The changes are appropriately documented (if applicable).~~
Adds electronReleaseServer to the Forge Config template so configuration can be read from environment variables.
=> Allow config for Electron Release Server to be read from envars

package.json, src/installers/darwin/dmg.js, src/installers/darwin/zip.js, src/makers/win32/appx.js, src/util/check-system.js, src/util/hdiutil.js, src/util/yarn-or-npm.js, test/slow/install-dependencies_spec_slow.js
Allows dependencies with carets to be escaped properly on Windows, which fixes the yarn installation problem documented in https://github.com/electron-userland/electron-forge-templates/issues/49#issuecomment-330581833.
=> fix(init): run package manager commands via cross-spawn

src/util/forge-config.js, test/fast/forge-config_spec.js, test/fixture/dummy_js_conf/forge.config.js
ISSUES CLOSED: #336 
Prevent hiding built-ins when proxying config. Previously a check to `hasOwnProperty` fail (since this is a built-in) and no value would be returned.
=> fix(generic): ensure config proxy doesn't prevent access to built-ins

package.json
There's currently a deprecation message when you install Forge:
```
npm WARN deprecated babel-preset-es2015@6.24.1: We're super 😸  excited that you're trying to use ES2015 syntax, but instead of continuing yearly presets 😭 , we recommend using babel-preset-env: npm install babel-preset-env. preset-env without options will compile ES2015+ down to ES5. And by targeting specific browsers, Babel can do less work and you can ship native ES2015+ to users 😎 ! Also, we are in the process of releasing v7, so give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and test it! Thanks so much for using Babel 🙏 , please give us a follow @babeljs for updates, join slack.babeljs.io for discussion and help support at opencollective.com/babel
```
=> chore(generic): replace the deprecated babel-preset-es2015 with babel-preset-env

src/api/import.js, src/api/package.js, src/api/start.js, test/fast/start_spec.js
* In `start`, throws an error when no app version exists.
* In `import`, warns when no app version exists.
Fixes #351.
=> Throw error/warn when no app version exists in start/import

src/api/package.js
Per https://github.com/electron-userland/electron-forge/issues/330#issuecomment-331743953
Also adds the feature of resolving `afterPrune` file hooks, to be consistent with the others.
In the `sqlite3` testcase in that issue that I have repro steps for, you still need to add `node-pre-gyp` to `devDependencies` in order to get it to finish running `npm run package` when `packageManager: 'yarn'`.
=> Move rebuild to post prune

src/util/check-system.js, test/fast/system_spec.js
I replaced `isNightlyYarnVersion`, but I'm not sure if we need to emit a warning in that case.
ISSUES CLOSED: #376
=> fix(generic): assume invalid semver package manager versions are incompatible

package.json, src/makers/linux/deb.js, src/makers/linux/flatpak.js, src/makers/linux/rpm.js, src/util/linux-config.js, test/fast/makers/deb_spec.js, test/fast/makers/dmg_spec.js, test/fast/makers/flatpak_spec.js, test/fast/makers/rpm_spec.js
This adds a new dependency, `lodash.merge`. Also adds fast tests for Linux maker config.
=> refactor(maker): DRY up linux config transformations

src/util/forge-config.js, test/slow/api_spec_slow.js
`yarn init` and `npm init` don't add a `productName` to `package.json`, and when running import on a project without a `productName`, the config setup would throw an exception, so guard against that. This also implements a very basic import unit test -- maybe we want more, but this at least covers this bug fix and other sanity-check-level issues.
=>  fix(importer): handle the case where productName doesn't exist

src/api/import.js
I noticed this typo, not sure if it's actually been causing anybody any issues.
=> fix(importer): Fix typo in dependency check

README.md
I didn't understand why setting the `arch` property in `electronPackagerConfig` was not supported, so I chatted briefly with @malept and came to understand that doing so creates complications regarding making that information available to each generator whereas specifying it on the command line makes it globally available. I added a short note to the `README.md` file to summarize this since I think it might be helpful to other developers who might want to understand why this is the case.
=> docs(packager): clarify why arch/dir/platform can't be set in Packager config

.appveyor.yml, .travis.yml, ci/Dockerfile, ci/docker.sh, ci/script.sh
* ~~The testsuite passes successfully on my local machine~~ (not applicable).
The addition of `import` tests make the macOS tests run dangerously close to the max execution time, so I did some general optimizations to the test environments.
* Cache `node_modules` in both CI environments
* Consolidate a bunch of the Docker-related CI scripts - for example, the intermediate Docker container wasn't necessary.
* Exclusively use Yarn in AppVeyor, since that's the only node installer that's being used in that CI environment anyway.
=> Improve CI runtimes

package.json, tabtab-install.js
* <del>The changes are appropriately documented</del> (not applicable).
* <del>The changes have sufficient test coverage</del> (not applicable).
Copies the installation code from tabtab, except it only warns instead of nonzero exits when an error occurs.
ISSUES CLOSED: #321
=> chore(generic): don't nonzero-exit when trying to install tabtab completions

src/init/init-npm.js, test/slow/api_spec_slow.js, tmpl/_compilerc
Forge changed to floats in #187 due to a break in `babel-preset-env`. The Babel folks added proper support for strings as versions in [v1.5.0](https://github.com/babel/babel-preset-env/blob/8d09fa52975e46e6244032abdb641ce5294474af/CHANGELOG.md#v150-2017-05-19) via https://github.com/babel/babel-preset-env/pull/321, about 1.5 months later (we require `^1.6.0` already).
Removes the following warning when running `electron-forge start`:
> Warning, the following targets are using a decimal version:
>
>   electron: 1.7
>
> We recommend using a string for minor/patch versions to avoid numbers like 6.10
> getting parsed as 6.1, which can lead to unexpected behavior.
=> fix(initializer): electron versions for babel-preset-env should be strings

src/api/import.js, src/api/package.js, src/init/init-npm.js, src/util/compile-hook.js, src/util/config.js, src/util/read-package-json.js, test/slow/api_spec_slow.js
Use `fs-extra`'s `readJson` and `writeJson` instead of rolling our own.
=> refactor(generic): Use readJson and writeJson from fs-extra

src/api/package.js, test/slow/api_spec_slow.js
=> fix(packager): package spinner isn't defined when asar.unpack is checked

src/api/make.js, src/api/package.js, src/api/publish.js, src/util/out-dir.js, test/fast/out-dir_spec.js
Allows you to specify either a build identifier or a function that fetches a build identifier that will be used to uniquely identify a set of builds.  This allows you to build multiple "channels" for your app in the same folder without overwriting each other.
=> feat(generic): allow specifying a build identifier that segregates build artifacts

src/publishers/s3.js
S3 publisher was failing to up the standard `.aws/credentials` file nor the standard `AWS_` env-vars. Instead it'd fail out early if you did not explicitly use the `package.json.config.s3` properties, which are preferred to env-vars/`credentials`.
May fix https://github.com/electron-userland/electron-forge/issues/259
=> Allow AWS credentials to be picked up from the environment or .aws/credentials file

src/util/hdiutil.js
cross-spawn-promise returns stdout as a buffer.
@zeke could you see if this fixes your problem? I'm kind of flying blind since I don't have a Mac.
Fixes #410.
=> fix(installer): hdiutil output should be a string

README.md, src/api/publish.js, src/publishers/electron-release-server.js, src/publishers/github.js, src/publishers/s3.js, test/fast/publish_spec.js
I added `dir` in preparation for the `snapcraft` publisher, and realized that there are way too many args for publisher modules. It makes more sense to have it be keyword args instead of positional.
BREAKING CHANGE:
Arguments for publisher modules have changed from positional to keyword.
=> [BREAKING CHANGE] feat(publisher): add dir to publisher args & convert args from positional to keyword

README.md, SUPPORT.md, package.json, src/makers/linux/snap.js, src/publishers/snapcraft.js, test/fast/makers/snap_spec.js, test/fast/makers_spec.js
Adds builtin support for making Snap distributables, and publishing them to the Snap store. Both are accomplished via [`electron-installer-snap`](https://github.com/electron-userland/electron-installer-snap) and the result of work done during the September 2017 Ubuntu Rally and January 2018 Snapcraft Summit.
Closes #25.
=> Integrated Snap support

README.md
* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-forge/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x ] The changes are appropriately documented (if applicable).
* [x ] The changes have sufficient test coverage (if applicable).
* [x ] The testsuite passes successfully on my local machine (if applicable).
The documentation of the publish API doesn't match the actual API as implemented in [/src/api/publish.js#L144](https://github.com/electron-userland/electron-forge/blob/master/src/api/publish.js#L144). This fixes the documentation in README.md.
=> docs(publisher): fix publisher api doc in readme

packages/publisher/electron-release-server/src/PublisherERS.js
=> feat(publisher): Allow to configure channel for ERS

.gitignore, .npmrc, package.json, src/api/make.js, src/api/package.js, src/api/start.js, src/util/get-electron-version.js, src/util/resolve-dir.js
* Replace [home-made RegEx](https://github.com/electron-userland/electron-forge/blob/012b152f94b04c4f4ba2aa27b23b572a846cd4b6/src/util/resolve-dir.js#L19) for testing whether or not the version string of `electron-prebuild-compile` with [`exact-version`](https://github.com/bendrucker/exact-version). 
- Since this functionality is not closely related to electron / electron-forge, I think it makes sense to use and external library instead. Even though it is relatively small, there are [a lot of subtleties that should have test coverage](https://github.com/jacobq/exact-version/blob/feat/support-commitish/test.js).
- The existing implementation does not correctly identify strings like `1.x`, `1.7.0 || 1.8.3`, or `1.0.0 - 1.5.0` as a range.
* Obtain electron version …
=> feat(generic): allow specifying electron-prebuilt-compile via URL

packages/publisher/s3/src/PublisherS3.js
Fixes #374 
Tests / Docs will come with v6 tests / docs.  This is gonna be a long process 😄
=> feat(publisher-s3): add keyResolver option to allow users to make their own S3 key path

packages/api/core/src/api/init-scripts/init-npm.js, packages/api/core/test/slow/api_spec_slow.js
Otherwise it points to `electron-forge@5`.
=> fix(core): install @electron-forge/cli to new projects

README.md
Point users to the 5.x docs for stable versions.
=> Add warning about master/6.x while it's under construction

package.json, packages/api/core/src/api/package.ts, packages/api/core/src/api/start.ts, packages/api/core/src/util/plugin-interface.ts, packages/api/core/test/fixture/dummy_js_conf/forge.config.js, packages/plugin/base/package.json, packages/plugin/base/src/Plugin.ts, packages/plugin/local-electron/package.json, packages/plugin/local-electron/src/Config.ts, packages/plugin/local-electron/src/LocalElectronPlugin.ts, packages/plugin/local-electron/test/LocalElectronPlugin_spec.ts, packages/utils/types/src/index.ts
Used to run a local version of electron instead of the version the electron module downloads
=> feat(plugin-local-electron): add plugin-local-electron

package.json, packages/maker/zip/package.json, packages/maker/zip/src/MakerZIP.ts
Replacing zip-folder to get rid of a dependency with a security vulnerability.
ISSUES CLOSED: #322
=> refactor(maker): replace zip-folder with cross-zip

packages/publisher/github/src/util/github.ts, packages/publisher/github/test/github_spec.ts
This broke with `@octokit/rest.js` 15.2.0.
Fixes #493.
=> fix(publisher-github): remove deprecated option from @octokit/rest params (6.x)

packages/api/core/src/api/import.ts, packages/api/core/src/api/init-scripts/init-npm.ts, packages/api/core/src/api/make.ts, packages/api/core/src/api/package.ts, packages/api/core/src/api/publish.ts, packages/api/core/src/api/start.ts, packages/api/core/src/util/forge-config.ts, packages/api/core/src/util/hook.ts, packages/api/core/src/util/plugin-interface.ts, packages/api/core/src/util/read-package-json.ts, packages/api/core/src/util/resolve-dir.ts, packages/api/core/test/fast/hook_spec.ts, packages/api/core/test/fast/publish_spec.ts, packages/api/core/test/fast/read-package-json_spec.ts, packages/api/core/test/fast/start_spec.ts, packages/api/core/test/slow/api_spec_slow.ts, packages/plugin/auto-unpack-natives/src/AutoUnpackNativesPlugin.ts, packages/utils/types/src/index.ts
In order to override fields like "version" at build time. This provides the ability
to intercept forge loading your package.json file and modify the JS object we read in
Docs: https://v6.electronforge.io/configuration#readpackagejson
=> feat(core): allow mutating packageJSON on load

packages/api/cli/script/vscode.cmd, packages/api/cli/script/vscode.sh
It must fix #535 because of the missed parent directory in vscode debugger scripts.
Please test it in Unix shell, because `*.sh` script double misses upper directory or it's intended behavior.
=> Finding right path to `electron-forge-start.js` for VSCode Debugger (fixing #535)

packages/api/core/src/util/forge-config.ts, packages/api/core/src/util/resolve-dir.ts
=> feat(core): allow no config to be present, default to an empty object

packages/api/core/src/util/forge-config.ts, packages/api/core/test/fast/forge-config_spec.ts, packages/api/core/test/fixture/dummy_js_conf/forge.config.js
Fixes #557 
Basically `typeof /foo/ === 'object'`
=> fix(core): stops breaking regexps in the config parser

packages/api/core/src/api/publish.ts, packages/api/core/test/fast/publish_spec.ts
=> fix(core): resolve publisher config correctly when given a publisher name

packages/api/cli/src/electron-forge-start.ts, packages/api/core/src/api/start.ts, packages/api/core/test/fast/start_spec.ts
Previously we weren't tracking application restarts in the CLI module or closing our stdin pipe once
the child app had quit
ISSUES CLOSED: #545
=> fix(core): keep track of application restarts and close stdin pipe correctly

packages/publisher/bitbucket/package.json, packages/publisher/bitbucket/src/Config.ts, packages/publisher/bitbucket/src/PublisherBitbucket.ts
=> feat(publisher-bitbucket): initial publish publisher-bitbucket

package.json, packages/maker/deb/package.json, packages/maker/deb/src/MakerDeb.ts, packages/maker/deb/test/MakerDeb_spec.ts, yarn.lock
=> fix(maker-deb): return the correct outPath with a prerelease version

package.json, src/makers/linux/deb.js, test/fast/makers/deb_spec.js
This is a backport of #584.
ISSUES CLOSED: #583
=> [5.x] fix(maker): return the correct outPath for a deb prerelease version

packages/api/core/src/util/install-dependencies.ts
* <del>The changes are appropriately documented</del> (not applicable).
* <del>The changes have sufficient test coverage</del> (not applicable).
* <del>The testsuite passes successfully on my local machine</del> (not applicable).
We used to have this when `--verbose` was set, but this should avoid some unnecessary GitHub issues
when it's always part of the exception.
The code change itself is based on looking at the [`cross-spawn-promise` usage](https://github.com/zentrick/cross-spawn-promise#usage).
=> fix(core): show the package manager stderr when installing deps fails

packages/api/core/test/slow/api_spec_slow.ts, packages/maker/wix/src/MakerWix.ts
=> fix(maker-wix): correct path to distributable

package.json, src/util/rebuild.js
Addresses #615.
6.x uses a different method of retrieving the Electron version and so should not be affected by this bug.
=> [5.x] fix(generic): throw an error when there's no node_modules folder in the project

package.json, test/slow/api_spec_slow.js
* [`electron-installer-debian`](https://github.com/electron-userland/electron-installer-debian/releases/tag/v1.1.0)
* [`electron-installer-snap`](https://github.com/electron-userland/electron-installer-snap/releases/tag/v3.1.0)
Cannot bump `-redhat` dependency due to breaking changes.
Addresses #654.
=> [5.x] chore(maker): force bump debian and snap dependencies to bring in fixes

packages/api/core/src/api/import.ts, packages/api/core/src/api/init-scripts/init-npm.ts, packages/api/core/src/api/make.ts, packages/api/core/src/api/package.ts, packages/api/core/src/api/start.ts, packages/api/core/src/util/electron-version.ts, packages/api/core/src/util/resolve-dir.ts, packages/api/core/src/util/upgrade-forge-config.ts, packages/api/core/test/fast/electron-version_spec.ts, packages/api/core/test/fast/upgrade-forge-config_spec.ts
Adds support for changing `config.forge` if it doesn't point to a JS file. In the future we could possibly provide `updateForgeConfig` for those JS files.
There was some refactoring involved - as a result, `getElectronVersion` has test coverage.
In general, the feature was written in such a way that it should have complete unit test coverage from a LoC perspective.
=> Add simple Importer from Forge 5.x to 6.x

packages/plugin/webpack/src/WebpackPlugin.ts
=> fix(plugin-webpack): make the PRELOAD_ENTRY variable map to undefined when there is no preload

packages/api/core/src/api/make.ts, packages/api/core/src/api/package.ts, packages/api/core/src/api/start.ts, packages/api/core/src/util/electron-version.ts, packages/api/core/src/util/resolve-dir.ts, packages/api/core/test/fast/electron-version_spec.ts, packages/api/core/test/fixture/non-exact/node_modules/electron/package.json
=> feat(core): add basic support for non-exact Electron versions

packages/maker/base/src/Maker.ts, packages/plugin/base/src/Plugin.ts, packages/publisher/base/src/Publisher.ts, packages/utils/types/src/index.ts
When I was researching #683, I found it odd that the abstract `Base` classes didn't implement the interfaces that are in use in `@electron-forge/core` when executing the plugins. If this is some TypeScript pattern, let me know and I'll update the PR to just have the empty `init()` method.
Fixes #683.
=> fix: abstract base classes should implement shared type interfaces

packages/api/core/src/api/init-scripts/init-git.ts, packages/api/core/test/slow/init_git_spec_slow.ts
I was running `v5.2.4` and `electron-forge init` to scaffold up a test project within an existing repository, and because I was running it within a subdirectory (rather than at the root of a repository) it didn't see the root `.git` directory, and instead initialized a Git repository inside a Git repository.
Not sure how many encounter this, but after remembering to cleanup this new `.git` directory a second time I got caremad enough to look at the code.
I added some tests to cover the scenarios that I think are important here (including the failing case I found), and ported `init-git` to use `git` itself to see whether you're in a repository.
Let me know if there's any extra work you'd like me to do while I'm in here, or if there's stuff I've indirectly …
=> use git to check that you're in a Git repository

packages/api/core/src/api/make.ts, packages/api/core/src/api/publish.ts, packages/api/core/src/util/plugin-interface.ts
I got a bit confused while I was converting a project to use Electron Forge via `import`.
=> fix(core): be more descriptive when a plugin/maker/publisher module isn't found

packages/plugin/webpack/src/WebpackPlugin.ts
This should only throw an error on `package`, not `start`.
Reference: https://webpack.js.org/api/node/#error-handling
ISSUES CLOSED: #579
=> fix(plugin-webpack): throw an error if webpack generates compilation errors when packaging

packages/plugin/webpack/src/Config.ts, packages/plugin/webpack/src/WebpackPlugin.ts
Allows the webpack plugin config entry `port` to override the default port number of `3000`, as that is a common port for various other dev servers.
This should be added to the v6 docs if merged.
ISSUES CLOSED: #691
=> fix(plugin-webpack): allow port to be configurable

README.md
'Usage' link in the main readme was pointing to a no longer existing '#usage' hash.
=> docs: 'Docs and Usage' link

yarn.lock
Updates `node-abi` to `2.8.0` for Electron 5 support.
=> chore: upgrade electron-rebuild deps, including node-abi

packages/api/core/test/slow/api_spec_slow.ts
=> chore(core): re-enable built-in template tests

packages/api/core/src/api/start.ts
=> fix(core): restart app in development via CLI multiple times

package.json
This was from way back in the beginning of Forge development, when it didn't depend on `electron-rebuild`.
=> chore: remove unnecessary direct node-gyp dependency

packages/api/core/tmpl/index.css, packages/api/core/tmpl/index.html, packages/template/webpack/src/WebpackTemplate.ts, packages/template/webpack/tmpl/renderer.js, packages/template/webpack/tmpl/webpack.renderer.config.js
Due to the change, we also need to add `style-loader`/`file-loader` plus the appropriate `import` magic to the renderer.
Fixes #941.
=> Move template CSS into a separate file

packages/plugin/webpack/src/WebpackPlugin.ts
=> fix(plugin-webpack): check that stats is not empty before sending to multi-logger

packages/plugin/webpack/src/WebpackPlugin.ts
When building an executable using `electron-forge make`, setting `publicPath` as `/` leads (for example) to `index.js` being referenced as `file:///main_window/index.js`, which cannot be found. (The URL points to `/main_window/index.js`, which is incorrect. It should be `../main_window/index.js`.)
When it is unset, the build runs properly and provides the correct URL. (This still works with `electron-forge start` ~~as well~~ _with manual reloading_.)
~~Removed the (apparently unnecessary) reference to `publicPath`.~~
Removed the reference to `publicPath` when building for production.
=> fix(plugin-webpack): properly reference `index.js` in production

packages/api/core/test/slow/api_spec_slow.ts, packages/template/webpack/src/WebpackTemplate.ts
Fixes the `index.css` problem in #1030.
Also refactors some of the code in there and adds relevant tests (although probably not in the right place).
=> Webpack template fixes

packages/api/cli/src/electron-forge-init.ts, packages/api/core/src/api/init-scripts/init-directory.ts, packages/api/core/src/api/init.ts, packages/api/core/test/slow/api_spec_slow.ts
Part of the [`electron/template` train :steam_locomotive:](https://github.com/electron-userland/electron-forge/pull/950), this lets us create a scheduled GitHub Action that updates the repository with the latest & greatest template.
=> feat(core): add "init --force" to allow overwriting an existing dir

packages/template/webpack/src/WebpackTemplate.ts, packages/template/webpack/tmpl/webpack.renderer.config.js
Instead of relying on the `style-loader/url`/`file-loader` pipeline, we use the `style-loader`/`css-loader` pipeline. This means the CSS ends up embedded in the JavaScript code generated by webpack, but it appears to work better.
=> fix(template-webpack): use css-loader instead of file-loader

package.json, packages/maker/base/package.json, packages/maker/base/src/Maker.ts, packages/maker/deb/src/MakerDeb.ts, packages/maker/flatpak/src/MakerFlatpak.ts, packages/maker/rpm/src/MakerRpm.ts, yarn.lock
Adds a method that checks for the binaries required for a maker to run. For example, `@electron-forge/maker-deb` requires `dpkg` and `fakeroot`.
Fixes #539.
=> fix(maker): allow Linux makers to run on non-Linux hosts if possible

packages/maker/deb/src/MakerDeb.ts, packages/maker/deb/test/MakerDeb_spec.ts, packages/maker/flatpak/src/MakerFlatpak.ts, packages/maker/flatpak/test/MakerFlatpak_spec.ts, packages/maker/rpm/src/MakerRpm.ts, packages/maker/rpm/test/MakerRpm_spec.ts, packages/maker/snap/src/MakerSnap.ts, packages/maker/snap/test/MakerSnap_spec.ts, packages/maker/zip/src/MakerZIP.ts
Fixes #1081
Previously some makers claimed the entire out directory as their out directory (`deb` and `rpm`) which resulted in subsequent calls to `ensureDirectory` wiping the entire out directory.
This PR ensures that all makers output things to their own directory + arch sub directory of the relevant platform supports both ia32 and x64.
=> fix: ensure that makers do not overwrite existing un-similar outputs

packages/plugin/webpack/src/WebpackPlugin.ts
Tried to bootstrap new Electron app with `elector-forge` (TS + `plugin-webpack`). Got such error:
```
An unhandled exception has occurred inside Forge:
log.debug is not a function
TypeError: log.debug is not a function
at /Users/project/node_modules/webpack-dev-middleware/lib/fs.js:63:21
at /Users/project/node_modules/graceful-fs/graceful-fs.js:57:14
at FSReqCallback.oncomplete (fs.js:153:23)
```
Thought it could be on my end and tried to create brand new project following setup guide:
```sh
$ yarn create electron-app my-new-app --template=webpack
```
It fail with same error as well. After checking where problem actually appears, found that `webpack-dev-middleware` has `log.debug` method in use: https://github.com/webpack/webpack-dev-middleware/blob/master/lib/f …
=> fix(plugin-webpack): add missing debug level for webpack-dev-middleware

.github/workflows/dependabolt.yml
The action migrates to GitHub Actions v2. There should be no difference in functionality.
=> build: use v2 of dependabolt

packages/api/core/test/fixture/native_app/package.json, packages/api/core/test/slow/api_spec_slow.ts, packages/api/core/test/slow/rebuild_spec_slow.ts
=> test(rebuild): sync native modules with the ones used in the electron-rebuild testsuite

packages/api/cli/package.json, packages/api/cli/src/electron-forge.ts, packages/api/cli/test/cli_spec.ts
Emit a warning and exit with status code 1.
Based on https://github.com/tj/commander.js/issues/1088#issuecomment-549018472
Example:
```bash
$ electron-forge foobar foo
✔ Checking your system
Unknown command "foobar foo".
See --help for a list of available commands.
```
Fixes #1300
Closes #1301 _(This is a simpler version, with an integration test added.)_
=> fix(cli): warn on unknown commands

package.json, packages/publisher/s3/package.json, packages/publisher/s3/src/PublisherS3.ts, yarn.lock
The `s3` module appears to no longer be maintained, which means, among other things, outdated dependencies.
I made an attempt to write tests for this, but it appears that `aws-sdk-mock` has issues mocking `S3.upload`, so I abandoned it.
Fixes #479.
=> refactor(publisher-s3): replace the s3 package with just aws-sdk

packages/api/core/test/slow/api_spec_slow.ts, packages/maker/appx/src/MakerAppX.ts, packages/maker/base/src/Maker.ts, packages/maker/base/test/version_spec.ts, packages/maker/squirrel/src/MakerSquirrel.ts, packages/maker/wix/package.json, packages/maker/wix/src/MakerWix.ts
The WiX and Squirrel makers don't handle prerelease information in the version, so we need to handle it in a similar manner to the AppX maker (except not making the user set a flag to normalize the version).
Fixes #1245.
=> fix(maker-windows): handle versions with prerelease information

packages/api/core/src/api/install.ts, packages/api/core/src/api/make.ts, packages/api/core/src/api/publish.ts, packages/api/core/test/fast/publish_spec.ts, packages/plugin/webpack/src/WebpackPlugin.ts
This is a more complete version of #1305.
Closes #1305.
=> refactor: replace indexOf with includes/startsWith where applicable

packages/api/core/tmpl/index.js, packages/template/webpack/src/WebpackTemplate.ts
=> fix(core): use loadFile instead of loadURL in the default template

packages/plugin/webpack/src/WebpackPlugin.ts, packages/plugin/webpack/test/WebpackPlugin_spec.ts
=> fix(plugin-webpack): handle package.json files without config keys

.github/workflows/ci.yml
@MarshallOfSound I'm disabling the docs job until the `NOW_TOKEN` variable is defined in the GitHub secrets for the repository.
=> build: disable docs CI step until NOW_TOKEN is defined

packages/api/cli/package.json, packages/api/cli/src/electron-forge-start.ts, packages/api/core/src/api/start.ts, packages/api/core/test/fast/start_spec.ts, packages/plugin/base/src/Plugin.ts, packages/plugin/webpack/src/WebpackPlugin.ts, packages/utils/types/src/index.ts
This avoids the `(process as any).restarted` idiom.
=> refactor: create the ElectronProcess type (ChildProcess + restarted property)

packages/template/typescript/src/TypeScriptTemplate.ts
Fixes up the scripts to set `main` in `package.json` to dist instead of baking it into the start script.
=> refactor(template-typescript): use main script to start app

packages/api/core/package.json, packages/api/core/test/slow/api_spec_slow.ts, packages/template/typescript-webpack/package.json, packages/template/typescript-webpack/src/TypeScriptWebpackTemplate.ts, packages/template/typescript-webpack/tmpl/index.ts, packages/template/typescript-webpack/tmpl/renderer.ts, packages/template/typescript-webpack/tmpl/tsconfig.json, packages/template/typescript-webpack/tmpl/tslint.json, packages/template/typescript-webpack/tmpl/webpack.main.config.js, packages/template/typescript-webpack/tmpl/webpack.plugins.js, packages/template/typescript-webpack/tmpl/webpack.renderer.config.js, packages/template/typescript-webpack/tmpl/webpack.rules.js
*  [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-forge/blob/master/CONTRIBUTING.md) for this project.
Adds a new template for Webpack + TypeScript.
cc @malept @MarshallOfSound
=> feat: add typescript-webpack template

package.json, packages/utils/web-multi-logger/package.json, packages/utils/web-multi-logger/src/Logger.ts, packages/utils/web-multi-logger/static/index.html, packages/utils/web-multi-logger/static/main.js, yarn.lock
Missed fixing breaking changes when doing the initial upgrade.
=> fix(web-multi-logger): xterm 4 compatibility

packages/template/typescript-webpack/tmpl/webpack.rules.js
`ts-loader` was not being loaded for TypeScript files.
Also, be more strict about the exclude regex.
ISSUES CLOSED: #1378
=> fix(template-typescript-webpack): adjust ts-loader module rule syntax

.github/workflows/ci.yml, yarn.lock
Also upgrades the Babel packages (as one of its sub-dependencies, `fsevents@^1.2.7` was blocking the build configuration from running).
=> build: re-enable the macOS/yarn CI tests

packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/src/WebpackPlugin.ts, packages/plugin/webpack/test/WebpackConfig_spec.ts, packages/plugin/webpack/test/WebpackPlugin_spec.ts, packages/plugin/webpack/test/fixtures/main_config_external/mainConfig.js
Splits out the Webpack config generation code to its own file, and adds basic test coverage.
=> refactor(plugin-webpack): move webpack config generation code to its own file

.github/workflows/ci.yml
See: https://github.com/actions/cache/blob/v1.1.0/examples.md#node---yarn
=> build: cache yarn directory instead of node_modules

packages/api/core/src/api/start.ts, packages/api/core/src/util/electron-version.ts, packages/api/core/test/fast/electron-version_spec.ts, packages/api/core/test/fast/start_spec.ts
=> fix(core): find electron when app is in a yarn workspace

packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/src/WebpackPlugin.ts
=> fix(plugin-webpack): lazily load config generator so isProd is set correctly

packages/template/typescript-webpack/tmpl/webpack.plugins.js
=> fix(typescript-webpack): remove async=false option from ts-checker to avoid preload compile hang

packages/api/core/test/slow/api_spec_slow.ts, yarn.lock
`asar` 2.1.0 contains a TypeScript definition, so use it.
=> build(deps-dev): upgrade asar to 2.1.0

packages/api/core/src/api/make.ts, packages/api/core/test/fixture/maker-wrong-platform.ts, packages/api/core/test/slow/api_spec_slow.ts
Currently, if there are no make targets for the given platform and make is run, it prints out:
```
Making for the following targets:
```
which is confusing. This PR notifies the user in the form of an exception that there are no make targets found.
Addresses #1514 (but unknown whether it fixes it at this time).
=> fix(core): throw an error when no make targets for the given platform are found

package.json, packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/test/WebpackConfig_spec.ts, yarn.lock
Added in [Webpack 4.33.0](https://github.com/webpack/webpack/releases/tag/v4.33.0).
See also:
* https://github.com/webpack/webpack/pull/9188
* https://v4.webpack.js.org/configuration/target/#target
=> fix(plugin-webpack): change preload target from electron-renderer to electron-preload

packages/template/base/tmpl/_travis.yml
Just things I noticed when I was looking at the Electron Fiddle CI config.
=> fix(template-base): update Travis CI config to best practices

packages/publisher/electron-release-server/package.json, packages/publisher/electron-release-server/src/PublisherERS.ts, packages/publisher/electron-release-server/test/PublisherERS_spec.ts
`node-fetch` doesn't fail when a `4xx` is raised (https://www.npmjs.com/package/node-fetch#handling-client-and-server-errors).
Our release process rely on this to make sure the files are properly updated during a `electron-forge publish`, but sometimes the Electron Release Server might send `4xx` or `5xx` errors and we are fooled into thinking "everything is ok" 🙂
Do not hesitate if you need more information !
=> fix(publisher-electron-release-server): throw an exception for 4xx/5xx HTTP status codes

packages/api/core/src/api/make.ts, packages/api/core/test/fast/make_spec.ts, packages/api/core/test/fixture/app-with-custom-maker-config/package.json, packages/api/core/test/fixture/custom-maker.ts
=> fix(core): overrideTargets inherit the named maker config in the Forge config

packages/publisher/s3/src/Config.ts, packages/publisher/s3/src/PublisherS3.ts
This PR adds the `endpoint` option what's adds the ability to change default S3 endpoint, to custom S3 instance. Also added `s3ForcePathStyle` and `region` for the same reasons.
=> feat(s3): add options to allow use custom instance

README.md
A few wording changes that were more professional to me as well as some formatting consistency with links and project slugs.
=> docs: clean up README wording

packages/maker/flatpak/src/MakerFlatpak.ts
Needed due to zypak sandboxing for Electron >= 5.
Corresponding docs update: https://github.com/MarshallOfSound/electron-forge-docs/commit/2aa0f59668d630e4100ac82129de53e154c63d06
Fixes #1702
=> fix(maker-flatpak): add eu-strip to required external binaries

packages/maker/snap/src/Config.ts
Try to make it more obvious where to put custom `snapcraft.yaml` config.
=> fix(maker-snap): allow MakerSnapConfig to also be SnapcraftConfig

packages/template/base/tmpl/index.js, packages/template/typescript-webpack/tmpl/index.ts, packages/template/typescript/tmpl/index.ts
I fixed the comment above the auto-quit prevention for macOS.
Before it suggested the code quits the app, now it says the code prevents the app from quitting.
**Note**: This same pull request was on [Electron \#24003](https://github.com/electron/electron/pull/24003). I added it here too for consistency.
=> docs(template): fix explanation of darwin auto-quit prevention

typings/sudo-prompt/index.d.ts
=> refactor: sudo-prompt provides its own typings

packages/api/core/src/api/package.ts, packages/api/core/test/slow/api_spec_slow.ts
Adds the following parameters to `postPackage`:
* `platform`
* `arch`
* `outputPaths` (the result of `await packager(...)`)
* `spinner` (the `ora` spinner, if defined)
Docs are at https://github.com/electron-forge/electron-forge-docs/pull/12
Also, DRYs up the "update `package.json`" code.
Fixes #1630.
=> feat(core): add params to the postPackage hook

package.json, packages/plugin/electronegativity/package.json, packages/plugin/electronegativity/src/ElectronegativityPlugin.ts, typings/@doyensec/electronegativity/index.d.ts, yarn.lock
Adds a first-party plugin for Electronegativity, which runs after packaging is done.
There is an [associated PR](https://github.com/electron-forge/electron-forge-docs/pull/13) for the `electronforge.io` docs.
=> feat: add electronegativity plugin

.github/dependabot.yml, packages/template/base/src/BaseTemplate.ts, packages/template/typescript-webpack/src/TypeScriptWebpackTemplate.ts, packages/template/typescript-webpack/tmpl/package.json, packages/template/typescript/src/TypeScriptTemplate.ts, packages/template/typescript/tmpl/package.json, packages/template/webpack/src/WebpackTemplate.ts, packages/template/webpack/tmpl/package.json
In theory this should allow Dependabot to upgrade the template `devDependencies` at the same time as the monorepo dependencies. If not, this will make it easier to write a GitHub Action to do so.
=> feat(template): move devDependencies to fake package.json for Dependabot

packages/publisher/github/src/Config.ts, packages/publisher/github/src/util/github.ts
Re-exporting TypeScript types results in broken JavaScript (the type doesn't exist in JS, resulting in a require error that's hidden by `@electron-forge/core`'s `require-search`).
Fixes #1951
=> fix(publisher-github): don't reexport Octokit type

packages/publisher/github/src/util/github.ts, packages/publisher/github/test/github_spec.ts
<details>
<summary>The following error was happening when using `@electron-forge/publisher-github`:</summary>
```
$ electron-forge publish --from-dry-run -d
⠋ Checking your system  electron-forge:check-system skipping system check +0ms
✔ Checking your system
electron-forge:publish attempting to resume from dry run +0ms
electron-forge:publish publishing for given state set +2ms
electron-forge:publish restoring publish settings from dry run +2ms
electron-forge:project-resolver searching for project in: /Users/michael/agoric/wallet +0ms
electron-forge:project-resolver electron-forge compatible package.json found in /Users/michael/agoric/wallet/package.json +1ms
⠋ Resolving publish target: @electron-forge/publisher-github  electron-forge:require-search searching [ …
```
=> fix(publisher-github): use new @octokit .auth property

packages/api/cli/src/util/check-system.ts
Also has a little refactor and adds a warning message.
=> fix(cli): don't hardcode the minimum required Node version

.mocharc.js, packages/plugin/webpack/package.json
Also fixes the description of the plugin.
Fixes #2013
=> chore(plugin-webpack): fix test script 

packages/template/typescript-webpack/tmpl/.eslintrc.json, packages/template/typescript/tmpl/.eslintrc.json
It's required config in typesctipt project.
https://github.com/benmosher/eslint-plugin-import#typescript
=> fix(template-typescript): add eslint-plugin-import/typescript rules

packages/template/typescript-webpack/tmpl/.eslintrc.json
Adds `.ts` / `.tsx` to the list of resolver node extensions to get rid of a lint error by default.
Closes electron-forge/electron-forge-docs#28
=> fix(template/typescript-webpack): add ts/tsx to known eslint-plugin-import extensions

packages/plugin/local-electron/src/LocalElectronPlugin.ts
=> fix(plugin-local-electron): bind methods correctly

packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/test/WebpackConfig_spec.ts
=> fix(webpack-plugin): add web as a target for the renderer process

tools/link-ts.ts
This should make it a bit easier to run tests for a given package, particularly when they need to use the top-level `typings` folder.
=> chore: set up typeRoots for package tsconfig

packages/api/core/test/slow/api_spec_slow.ts
Re-enabled after upgrading transitive dependencies (I guess the older node-abi dependency was causing it to hang??). Also refactored so it's more self-contained and more idiomatic Mocha.
=> test(core): re-enable & refactor native module test

packages/plugin/webpack/src/Config.ts, packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/test/WebpackConfig_spec.ts
Fixes #2293.
Closes #2322.
Needs docs to be added to the [Webpack plugin guide](https://www.electronforge.io/config/plugins/webpack).
=> feat(plugin-webpack): add nodeIntegration config for renderers

packages/plugin/webpack/src/Config.ts, packages/plugin/webpack/src/WebpackPlugin.ts
Fixes #2331 (probably). At the very least, it allows for a workaround.
This is difficult to test automatically, because it's an option passed to `webpack-dev-server`.
This needs to be documented in the Webpack plugin guide.
=> feat(plugin-webpack): add devContentSecurityPolicy config option

packages/maker/squirrel/src/MakerSquirrel.ts
Fixes a bug reported in Discord.
**Steps to reproduce**:
```shell
npx create-electron-app example-app
cd example-app
```
Update package.json and merge the following instructions in:
```json
{
"productName": "My Example App",
"config": {
"forge": {
"packagerConfig": {
"executableName": "MyExampleApp"
}
}
}
}
```
**Expected**: Squirrel installer finds `MyExampleApp.exe`
**Actual**: Squirrel installer tries and fails to look for `My Example App.exe`.
**Solution**: fix the default `exe` option to check `forgeConfig.packagerConfig.executableName` first.
=> fix(maker-squirrel): use executableName for exe when available

packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/src/WebpackPlugin.ts, packages/plugin/webpack/test/WebpackPlugin_spec.ts
Follow-up from #2225:
* Code refactors for clarity
* Removes the webpack-dev-server test, because it caused the testsuite to `process.exit()` early. This will likely be rewritten after #2320 lands since it has better support for webpack-based integration tests.
=> refactor(plugin-webpack): cleanup

packages/plugin/webpack/src/WebpackPlugin.ts
Do the same as the renderer do, report and exit if all going bad
=> fix(plugin-webpack): throw error if something bad happened in preload compilation

packages/plugin/electronegativity/src/ElectronegativityPlugin.ts
In the `1.8.0` version of Electronegativity (6 months old 😐), added the option `parserPlugins`, which for programmatic usage doesn't have a default value, this PR provides the default value which used in the CLI interface, an empty array. Not sure if this is an upstream bug, but if needed I can try to upstream this change.
=> fix(plugin-electronegativity): add `parserPlugins` option

packages/api/core/src/api/package.ts, packages/api/core/src/api/start.ts
This adds `platform` and `arch` parameters to the `generateAssets` hook so it can be used to generate or copy native assets.
```ts
{
hooks: {
generateAssets: async (config: ForgeConfig, platform: string, arch: string) => {
console.log('We should generate some assets here');
}
}
}
```
=> feat(core): add `platform` and `arch` to `generateAssets` hook parameters

packages/api/core/src/util/electron-version.ts, packages/api/core/test/fast/electron-version_spec.ts, packages/api/core/test/fixture/yarn-workspace/packages/electron-folder-in-node-modules/node_modules/electron/package.json, packages/api/core/test/fixture/yarn-workspace/packages/with-node-modules/node_modules/some-other-module-second/package.json, packages/api/core/test/fixture/yarn-workspace/packages/with-node-modules/node_modules/some-other-module/package.json
This PR tries to fix the case in using with `yarn workspaces` where yarn also creates a `node_modules` folder inside the package directory with `.bin` files. This adds a `packageName` when searching for the `node_modules` directory to find the folder with the electron inside.
=> fix(core): search for electron in a `node_modules` folder with electron in it

CONTRIBUTING.md, tools/bump.js, tools/bump.ts
Convert bump script to TypeScript, add convenience function, and avoid using `util.promisify`.
=> refactor(bump): convert to TypeScript

packages/template/base/package.json, packages/template/base/src/determine-author.ts, packages/template/base/test/determine-author_spec.ts
Reduce the amount of uses of `util.promisify` because it's problematic in newer versions of TypeScript.
=> refactor(template-base): replace exec/promisify with @malept/cross-spawn-promise

packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/src/util/AssetRelocatorPatch.ts, packages/plugin/webpack/test/AssetRelocatorPatch_spec.ts
=> fix(webpack-plugin): Ensure asset relocator injected code works with nodeIntegration disabled

packages/template/typescript-webpack/package.json, packages/template/typescript-webpack/tmpl/.eslintrc.json, packages/template/typescript/tmpl/.eslintrc.json
* Add `import/electron` settings
* Update import config to use `recommended` over `errors` + `warnings`
* Remove redundant settings
* Add proper test script to the `typescript-webpack` template module
Closes #2142.
=> fix(template): add plugin:import/electron to TypeScript ESLint config

packages/plugin/webpack/src/WebpackPlugin.ts
=> fix(plugin-webpack): don't show the error message if packagerConfig.ignore is a function

packages/plugin/webpack/src/WebpackConfig.ts
Specify modules in resolve will cause application not resolve to correct version of dependencies
Fixes #1845.
FIxes #1929.
=> fix(plugin-webpack): don't specify resolve.modules by default

packages/maker/dmg/package.json, packages/maker/dmg/src/MakerDMG.ts, packages/maker/dmg/test/MakerDMG_spec.ts
As reported in Discord, publishing both arm64 and x64 DMGs are by default difficult because it's named the same despite being built for different architectures. This adds the target arch to the default DMG basename.
=> fix(maker-dmg): add the arch to the default dmg name

packages/plugin/webpack/src/Config.ts, packages/plugin/webpack/src/WebpackPlugin.ts, packages/plugin/webpack/test/WebpackPlugin_spec.ts
Fixes #594.
Fixes #2308.
Fixes #2413.
=> feat(plugin-webpack): allow most webpack-dev-server options to be configurable

packages/api/core/src/util/electron-version.ts, packages/api/core/test/fast/electron-version_spec.ts, packages/api/core/test/fixture/npm-workspace/node_modules/electron/package.json, packages/api/core/test/fixture/npm-workspace/package.json
Fixes #2306.
Also does a refactor of the electron version tests for clarity and scoping of test variables. They were kind of in a weird state since we do not run the testsuite for each `NODE_INSTALLER` anymore.
=> fix(core): add support for finding electron for npm 7 workspaces

packages/template/typescript-webpack/tmpl/webpack.rules.js, packages/template/webpack/tmpl/webpack.rules.js
Apparently the asset relocator loader generates "fake" `.node` files which are actually JS files that point toward the relocated native modules in `native_modules/`. Since they're not actually native code, we can't have `node-loader` load them. To fix this, adjust the default test for the `node-loader` to only pick up `.node` modules in a `native_modules` folder. (This can be adjusted as necessary by the Electron app author).
=> fix(template-webpack): only use node-loader if the .node files are in native_modules/

package.json, packages/plugin/webpack/package.json, packages/plugin/webpack/src/WebpackPlugin.ts, typings/webpack-dev-server/index.d.ts, yarn.lock
It looks like between `webpack-dev-server` 4.0.0-rc.0 and 4.0.0, they added some API deprecations/breakage. This updates all that based on the [migration docs](https://github.com/webpack/webpack-dev-server/blob/v4.0.0/migration-v4.md).
Fixes #2456
=> fix(plugin-webpack): fix deprecation warnings for dev-server@4.0.0

packages/api/core/src/api/make.ts, packages/api/core/test/fast/make_spec.ts, packages/api/core/test/fixture/maker-name-wrong-type/package.json, packages/api/core/test/fixture/maker-sans-name/package.json
Reduces the amount of questions such as #2466.
=> fix(core): better errors when maker names are invalid

.github/dependabot.yml, package.json, packages/api/cli/src/electron-forge-start.ts, packages/api/core/src/api/init-scripts/find-template.ts, packages/api/core/src/api/init-scripts/init-git.ts, packages/api/core/src/api/make.ts, packages/api/core/src/api/package.ts, packages/api/core/src/util/install-dependencies.ts, packages/api/core/src/util/require-search.ts, packages/api/core/src/util/resolve-dir.ts, packages/publisher/github/src/PublisherGithub.ts, packages/publisher/github/src/util/no-release-error.ts, packages/utils/test-utils/src/index.ts, tools/update-dependencies.js, typings/sudo-prompt/index.d.ts, yarn.lock
Unblocked TypeScript updates by copy/pasting (and modifying) a promisify declaration for `sudo-prompt` from an [unmerged PR](https://github.com/jorangreef/sudo-prompt/pull/124).
=> build(deps-dev): upgrade typescript to ~4.4.2

.github/dependabot.yml, package.json, packages/publisher/s3/package.json, packages/publisher/s3/src/PublisherS3.ts, yarn.lock
Also fixes the credentials bug since this PR will cause a merge conflict with it.
Fixes #2226.
Closes #2258.
=> refactor(publisher-s3): use AWS-SDK v3

packages/publisher/github/package.json, packages/publisher/github/src/util/github.ts, packages/publisher/github/test/github_spec.ts
Hooks the `debug` module into [Octokit's logging mechanism](https://octokit.github.io/rest.js/v18#logging). You can enable info messages by adding `electron-forge:publisher:github:info` to the `DEBUG` environment variable, and debug messages by adding `electron-forge:publisher:github:debug` to the `DEBUG` environment variable. Please note that both will be enabled if you already have `electron-forge:*` in the `DEBUG` environment variable.
Also does some cleanup while working on the module (namely, using the `userAgent` option instead of setting a header).
Addresses #2498.
Fixes #1672.
Closes #1673.
=> feat(publisher-github): add debug support for Octokit

package.json, packages/api/core/package.json, packages/utils/types/package.json, tools/update-dependencies.js, yarn.lock
=> fix: unpin electron-notarize

packages/plugin/webpack/package.json, packages/plugin/webpack/src/WebpackPlugin.ts, packages/plugin/webpack/test/WebpackPlugin_spec.ts
=> fix(plugin-webpack): validate that the correct entry point is used

package.json, packages/publisher/github/package.json, packages/publisher/github/src/util/github.ts, packages/publisher/github/test/github_spec.ts, yarn.lock
Add retry support as per https://octokit.github.io/rest.js/v18#automatic-retries
=> feat(publisher-github): add retry support

.eslintrc.json, packages/api/cli/src/electron-forge.ts
Fixes #2670 and the eslint(-plugin-node) rule that caused it.
See also: https://github.com/mysticatea/eslint-plugin-node/blob/v11.1.0/docs/rules/shebang.md
=> fix(cli): re-add shebang to electron-forge binary

packages/publisher/electron-release-server/src/PublisherERS.ts
closes: #1873
The RELEASES file is now filtered out from the artifacts and thus not send to electron release server.
=> fix(publisher-electron-release-server): omit RELEASES file when uploading assets

packages/plugin/webpack/src/Config.ts, packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/test/WebpackConfig_spec.ts
Allows you to specify a seperate webpack config for the preload process. This is 100% necessary in order to use react refresh see: 
https://github.com/electron-userland/electron-forge/issues/1936 
https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/263
There is a pr open for this currently but the author appears to have abandoned it. This is blocking me so lets get this fixed. I am happy to write documentation for it if needed.
=> feat(plugin-webpack): allow specifing a seperate webpack config for your preload

packages/maker/wix/src/Config.ts
feat: Make autoUpdate and autoLaunch features configurable in MakerWixConfig
- Added `features` property to `MakerWixConfig` to enable configuration of `autoUpdate` and `autoLaunch` features
- (see `electron-wix-msi`'s `Features` definition [here](https://github.com/felixrieseberg/electron-wix-msi/blob/master/src/creator.ts#L85))
- These features can then be configured by adding `features` to `@electron-forge/maker-wix`'s `config` in `forge.config.js`
- Example: `features: { autoUpdate: true, autoLaunch: false }`
=> feat: Make autoUpdate and autoLaunch features configurable in MakerWixConfig

package.json, tools/publish.js, tools/sync-readmes.ts, yarn.lock
Does what it says on the tin. Removes some pretty old transitive devDependencies from `yarn.lock`.
=> refactor: replace listr with listr2, which has updated deps

.github/workflows/ci.yml
Use `windows-latest` (currently 2022) instead of `windows-2019`. Needs a very recent version of `node-gyp`.
=> ci(fast): use windows-latest

packages/publisher/electron-release-server/src/PublisherERS.ts
closes: #2087
Resubmitting #2088 after rebasing.
=> fix(publisher-electron-release-server): set knownLength option for asset upload

packages/publisher/electron-release-server/src/Config.ts, packages/publisher/electron-release-server/src/PublisherERS.ts, packages/publisher/electron-release-server/test/PublisherERS_spec.ts
Closes #1215 
Adds support for the `flavor` config in `electron-release-server`. This is an optional parameter for the ERS publisher. Also added a set of basic tests for the publisher.
=> feat(publisher-ers): support flavor config

packages/plugin/webpack/test/fixtures/apps/native-modules/package-lock.json, packages/publisher/electron-release-server/package.json, packages/publisher/electron-release-server/test/PublisherERS_spec.ts
**Summarize your changes:** #2766 added some tests to the trunk that were broken because #2706 added new code paths that weren't accounted for in the mocks.
=> test(publisher-ers): fix fs-extra mocks

packages/plugin/webpack/src/Config.ts, packages/plugin/webpack/src/WebpackPlugin.ts, packages/plugin/webpack/test/WebpackPlugin_spec.ts
Stop including source maps in a packages application by default.
Add `packageSourceMaps` to `WebpackPluginConfig` allow source maps to be included in the packaged application.
✅ Closes: #2573
Add a configuration option to `WebpackPluginConfig`:
```javascript
packageSourceMaps?: boolean;
```
Update the `forgeConfig.packagerConfig.ignore` function in `WebpackPlugin.resolveForgeConfig` to return `true` if the filename ends in `.js.map` unless the above configuration option is set to `true`.
=> feat: 🎸 Add packageSourceMaps option to WebpackPluginConfig

packages/api/core/src/api/make.ts, packages/api/core/test/fast/make_spec.ts, packages/api/core/test/fixture/app-with-maker-disable/package.json, packages/utils/types/src/index.ts
=> feat: allow disabling maker in config

packages/publisher/github/src/Config.ts, packages/publisher/github/src/PublisherGithub.ts
Add configuration option `tagPrefix`, that if set, overrides the default
"v" when determining the corresponding tag name for GitHub releases.
✅ Closes: #1790
=> feat: 🎸 allow specifying alternative tag prefix

packages/plugin/webpack/src/Config.ts, packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/src/WebpackPlugin.ts, packages/plugin/webpack/src/util/processConfig.ts, packages/plugin/webpack/test/AssetRelocatorPatch_spec.ts, packages/plugin/webpack/test/WebpackConfig_spec.ts, packages/plugin/webpack/test/util/processConfig_spec.ts
Another take at #1556 for Webpack 5
=> feat(webpack-plugin): webpack 5 configuration factory

packages/api/core/src/api/start.ts, packages/utils/async-ora/src/ora-handler.ts
As a side-effect of using `node:readline`, when `ora` completes it may `pause` `stdin`. Once it is in this paused state, it is impossible to truly revert to the original "unpaused" state as calling `resume` on `stdin` has its own side-effect of keeping the node process alive as long as `stdin` remains unpaused (which is different than the default, where stdin is both unpaused but will not keep the process alive).
To get around this, I added a flag on `asyncOra` that will maintain `stdin`'s unpaused state across ora's completion, but only for cases where that behavior is desirable, like the `electron-forge start` which both reads from `stdin` and is meant to stay alive "forever".
Fixes #2319.
=> fix: keep stdin unpaused after ora completes

packages/plugin/webpack/src/Config.ts, packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/src/WebpackPlugin.ts, packages/plugin/webpack/test/AssetRelocatorPatch_spec.ts, packages/plugin/webpack/test/WebpackConfig_spec.ts, typings/webpack-dev-server/index.d.ts
Summarize your changes:
Note that this replaces https://github.com/electron-userland/electron-forge/pull/2856 based on [this suggestion](https://github.com/electron-userland/electron-forge/pull/2856#issuecomment-1146258778).
We have multiple BrowserWindows in our project, some which use `nodeIntegration: false` and some which use `nodeIntegration: true`.
Without this change we get the error require is not defined at runtime in the BrowserWindows with nodeIntegration: false.
We didn't need to do this with older versions of `@electron-forge/plugin-webpack` that used Webpack 4 where we could simply not import any Node JS modules and just use browser-targeted modules.
`@electron-forge/plugin-webpack` only allows us to set one target for all entrypoints. This change …
=> feat(plugin-webpack): Allow each entrypoint to specify `nodeIntegration`

package.json, packages/api/cli/package.json, packages/api/core/package.json, yarn.lock
Bumps @electron/get to 2.0.0. This is not marked as a breaking change, because the required version of Node for Forge is currently 14+ (@electron/get's new version requires at least 12+)
=> build: update @electron/get to 2.0.0

packages/template/typescript-webpack/src/TypeScriptWebpackTemplate.ts
I added the preload script to the package.json file, so it would get compiled by Webpack. When you initialize the project it does not work, because the file is not compiled by Webpack. This change would solve this, by adding it to the compiler.
closes #2935
=> fix(template-typescript-webpack): preload file to webpack config

packages/template/typescript-webpack/package.json, packages/template/typescript-webpack/src/TypeScriptWebpackTemplate.ts, packages/template/typescript-webpack/test/TypeScriptWebpackTemplate_spec.ts, packages/template/typescript/package.json, packages/template/typescript/src/TypeScriptTemplate.ts, packages/template/typescript/test/TypeScriptTemplate_spec.ts
When `preload` was added to the Forge templates, the TypeScript templates actually ended up with both a `preload.js` and a `preload.ts` because the base template adds `preload.js` and the TypeScript template adds a `preload.ts`. This PR modifies the TS templates to remove the `preload.js` just like it already removes the `index.js`.
I also modified the template tests to verify that no js files end up in the `src/` folder after the TypeScript templates are applied. That way if any other new files are added in the future, the tests will automatically verify that only the TypeScript versions are applied.
=> feat: remove preload.js from TypeScript templates

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/pull_request_template.md, .github/workflows/ci.yml, .github/workflows/gh-pages.yml, CONTRIBUTING.md, README.md, packages/maker/flatpak/src/Config.ts, packages/template/base/tmpl/_appveyor.yml
=> chore: migrate master main

.github/workflows/ci.yml
The older 18.04 environment is deprecated by GitHub Actions.
=> ci: upgrade slow tests to ubuntu-20.04 environment

packages/maker/base/src/Maker.ts, packages/plugin/base/src/Plugin.ts, packages/publisher/base/src/Publisher.ts, packages/utils/types/src/index.ts, tools/gen-docs.ts
Makes the API docs a _bit_ better by tweaking the settings.
* The site name is prettier and contains the version now.
* Any class members with the `@internal` comment is now ignored.
See preview: https://astounding-pegasus-a7d11f.netlify.app/
=> docs: additional typedoc improvements

package.json, packages/maker/pkg/package.json, packages/maker/pkg/src/Config.ts, packages/maker/pkg/src/MakerPKG.ts, packages/maker/pkg/test/MakerPKG_spec.ts, yarn.lock
Swaps out the old `electron-osx-sign` package for the newer `@electron/osx-sign` one. Closes #2957
Breaking change: `identity-validation` flag is camelCased to `identityValidation` now.
=> feat!(maker-pkg): upgrade to `@electron/osx-sign`

.github/workflows/ci.yml, .github/workflows/gh-pages.yml
This PR makes two changes to CI:
* Updates existing GH actions to remove the `save-state` deprecation warning (fixes #2955)
* Pins GH actions to a SHA rather than a tag (the corresponding tag has been left as a comment)
=> fix: pin gh-actions to SHAs, update to remove deprecation warning

packages/api/core/src/api/make.ts, packages/api/core/src/api/package.ts, packages/api/core/src/api/publish.ts, packages/api/core/src/api/start.ts, packages/api/core/src/util/forge-config.ts, packages/api/core/src/util/plugin-interface.ts, packages/api/core/src/util/upgrade-forge-config.ts, packages/api/core/test/fast/forge-config_spec.ts, packages/api/core/test/fast/publish_spec.ts, packages/api/core/test/fast/read-package-json_spec.ts, packages/api/core/test/fast/upgrade-forge-config_spec.ts, packages/plugin/webpack/src/WebpackPlugin.ts, packages/utils/types/src/index.ts
Couple of breaking changes to improve DX
* Plugins now follow the same syntax as makers/publishers
* Better type safety of the core make/publish APIs
* Renamed electronRebuildConfig to rebuildConfig
* Fixed types for packagerConfig and rebuildConfig to appropriately Omit certain forge provided keys
With better types we can do some work to allow `forge.config.ts` and a completely type-safe config 🪄
=> feat!: improve forge configuration DX

.github/workflows/gh-pages.yml
As discussed in today's Ecosystem WG meeting.
cc @VerteDinde @malept @dsanders11
=> fix(docs): only publish API docs on v6 tags

tools/gen-docs.ts
Adds `'**/node_modules/typescript/**'` to the settings for TypeDoc so we don't export internal TypeScript utility types like `Record` or `Omit`.
=> fix(docs): avoid generating Typescript utility types

tools/gen-docs.ts, tools/utils.ts
Two small fixes:
* Better type for `package.json` in our utility code
* Doesn't attempt to run TypeDoc for a package if it doesn't have a `main` entry. Removes a warning message `Warning: Could not determine the entry point for "/Users/erick.zhao/Developer/electron/forge/packages/api/cli/package.json". Package will be ignored.`
=> fix(docs): only load modules if package has entry point

SUPPORT.md, package.json, packages/api/core/package.json, packages/api/core/src/api/import.ts, packages/plugin/webpack/package.json, packages/utils/types/package.json, tools/update-dependencies.js, yarn.lock
This PR upgrades our usage of Electron Packager to v17. The biggest change here is that we end up using `@electron/osx-sign` rather than `electron-osx-sign`.
Should be accompanied with a docs change as well.
=> feat!: upgrade electron-packager@17

packages/template/typescript-webpack/src/TypeScriptWebpackTemplate.ts
=> fix(template-typescript-webpack): use new plugin syntax

packages/template/webpack/src/WebpackTemplate.ts
=> fix(template-webpack): use new plugin syntax

package.json, yarn.lock
Husky would be great if we actually set it up 🙃
=> build: actually enable husky/lint-staged

.eslintrc.json, packages/api/core/src/api/publish.ts, packages/api/core/src/util/plugin-interface.ts, packages/maker/base/test/config-fetcher_spec.ts, packages/plugin/local-electron/test/LocalElectronPlugin_spec.ts, packages/plugin/webpack/test/WebpackPlugin_spec.ts
Missed a few in #2996 and found a handy rule so we don't miss any again
=> build: add rule that enforces named exports over default exports

.gitignore, package.json, packages/maker/appx/README.md, packages/maker/deb/README.md, packages/maker/dmg/README.md, packages/maker/flatpak/README.md, packages/maker/pkg/README.md, packages/maker/rpm/README.md, packages/maker/snap/README.md, packages/maker/squirrel/README.md, packages/maker/wix/README.md, packages/maker/zip/README.md, packages/plugin/auto-unpack-natives/README.md, packages/plugin/compile/README.md, packages/plugin/compile/src/CompilePlugin.ts, packages/plugin/electronegativity/README.md, packages/plugin/local-electron/README.md, packages/plugin/webpack/README.md, packages/publisher/bitbucket/README.md, packages/publisher/electron-release-server/README.md, packages/publisher/github/README.md, packages/publisher/nucleus/README.md, packages/publisher/s3/README.md, packages/publisher/snapcraft/README.md, tools/gen-docs.ts, tools/publish.js, yarn.lock
Co-authored-by: Keeley Hammond <vertedinde@electronjs.org>
This PR adds more detailed READMEs to each Forge module.
Deployed live here at https://add-readmes--marvelous-choux-77d0b7.netlify.app/
=> docs: add READMEs to packages

packages/publisher/s3/src/Config.ts, packages/publisher/s3/src/PublisherS3.ts
- add a `sessionToken` option
- change the fallback to use the credential provider chain
Fixes #2983
=> feat(publisher-s3): Add sessionToken and change default fallback

packages/api/core/src/api/import.ts, packages/api/core/src/api/init.ts, packages/api/core/src/util/forge-config.ts, packages/api/core/test/fast/forge-config_spec.ts, packages/api/core/test/slow/api_spec_slow.ts, packages/maker/squirrel/src/MakerSquirrel.ts, packages/template/base/tmpl/package.json
Makes some code a lot simpler ❤️
=> refactor(maker-squirrel): ensure Squirrel.Windows `name` doesn't contain hyphens

packages/plugin/webpack/src/WebpackPlugin.ts
As mentioned in https://github.com/electron/forge/issues/2818#issuecomment-1207299969, the Webpack plugin sets the `devDependencies`, `dependencies`, `optionalDependencies` and `peerDependencies` objects to `{}` in the distributed package.json. If any other plugin runs after the Webpack plugin and tries to read one of these objects, it will get an empty object instead of the actual dependencies, which seems like an unexpected side-effect.
Fixes https://github.com/electron/forge/issues/2818.
=> fix(plugin-webpack): keep `devDependencies`, `dependencies`, `optionalDependencies` and `peerDependencies` in the distributed package.json

CONTRIBUTING.md, package.json, packages/maker/wix/package.json, yarn.lock
Incorporates breaking icon name changes.
=> chore: bump electron-wix-msi to 5.0.0

packages/api/core/src/api/import.ts, packages/api/core/src/api/init-scripts/init-git.ts, packages/api/core/src/util/forge-config.ts, packages/api/core/test/fast/forge-config_spec.ts, packages/api/core/test/slow/api_spec_slow.ts, packages/template/base/src/BaseTemplate.ts, packages/template/base/tmpl/forge.config.js, packages/template/base/tmpl/package.json, packages/template/typescript-webpack/src/TypeScriptWebpackTemplate.ts, packages/template/typescript-webpack/tmpl/forge.config.ts, packages/template/webpack/src/WebpackTemplate.ts, packages/template/webpack/tmpl/forge.config.js
This change affects the `init` and `import` commands. It changes these commands to create a `forge.config.js` rather than creating `config.forge` in your package.json.
This is considered a breaking change for any third-party templates because the base template no longer sets up a `config.forge` object, and any template-specific mutations to the Forge config should instead be performed on the `forge.config.js` file.
Ref #2973
=> feat!: prefer forge.config.js over package.json config

packages/template/typescript-webpack/tmpl/forge.config.ts
ref https://github.com/electron/forge/pull/3012#issuecomment-1294420816
In https://github.com/electron/forge/pull/2991, I copy/pasted the webpack config over but failed to change the entrypoint extensions over from `.js` to `.ts`.
=> fix(template-typescript-webpack): webpack entrypoint extensions

packages/template/typescript-webpack/tmpl/package.json
Our usage of `rechoir` introduced in #2993 was actually broken. Running the TypeScript Webpack template yields the following error when attempting to load `forge.config.ts` with `rechoir`.
```
An unhandled rejection has occurred inside Forge:
Error: Unable to use specified module loaders for ".ts".
Electron Forge was terminated. Location:
{}
error Command failed with exit code 1.
```
Run the `init` command with `--template=typescript-webpack` and attempt to run `yarn start`.
Add `ts-node` as a dev dependency for the template.
As per the [rechoir](https://github.com/gulpjs/rechoir) docs, rechoir needs a local installation of the ts -> js transformer to run.
> **Note**
> While rechoir will automatically load and register transpilers like coffee-script, you must provide a local installation. …
=> fix(template-typescript-webpack): properly load `forge.config.ts`

packages/maker/wix/src/Config.ts, packages/maker/wix/src/MakerWix.ts
This PR exposes icon in the MakerWixConfig interface.
_Note: We should refactor how options are passed here, so we're not using a duplicated interface over MSICreatorOptions, but I'll avoid doing that right before stable release._
=> build: add icon property to MakerWixConfig

packages/plugin/webpack/src/WebpackPlugin.ts
Per https://github.com/electron/forge/pull/2995#issuecomment-1296079778
This was lost accidentally, we need better webpack plugin tests 🤔
=> fix: restore isProd in the webpack  plugin

packages/api/core/src/util/resolve-dir.ts
We were falling back to the "best guess" behavior for the forge.config.js scenario, we can do better than best guess and infer a forge project based on a forge dependency
=> fix: use @electron-forge/cli hint for project resolution

packages/template/base/src/BaseTemplate.ts
This PR ensures that the most recent compatible version of `@electron-forge/plugin-webpack` will be installed by `create-electron-app`. While the `package.json` might still show an older version when using `create-electron-app` (as outlined in https://github.com/electron/forge/issues/3019#issuecomment-1297307522), the version `yarn` / `npm` will actually install is the most recent.
=> fix(template-base): use minimum instead of exact version when replacing `ELECTRON_FORGE/VERSION` in templates

tools/publish.js
Currently, a large number of source/development files (`.ts`/`.map`/etc.) from most packages is being published to npm.
The `plugin-webpack` package is even publishing its entire `test` folder with a test app, including its `node_modules`:
This PR addresses the problem by writing a `.npmignore` file to each package folder before publishing, and then removing the file afterwards. `.ts` (except `.d.ts` type definitions), `tsconfig.json`, `.map` and `.tsbuildinfo` files, as well as any `/test` folders, are now ignored.
Since the `.gitignore` in the project root has `.npmignore`, I thought writing and then deleting the files would be an acceptable approach (not to mention easier to review), but actually adding the `.npmignore` files to Git would be trivial if …
=> fix(publish): ignore unnecessary files when publishing to npm

tools/publish.js
Modifies the generated ts-ignores to ignore /test and /src
=> build: modify ts-ignore for /test & /src

packages/template/webpack-typescript/tmpl/webpack.main.config.ts, packages/template/webpack-typescript/tmpl/webpack.plugins.js, packages/template/webpack-typescript/tmpl/webpack.plugins.ts
=> fix: ensure webpack typescript template runs

packages/api/core/src/api/make.ts
=> chore(utils): make `require-search` error message clearer

packages/template/webpack-typescript/package.json, packages/template/webpack-typescript/test/WebpackTypeScript_spec_slow.ts, packages/utils/test-utils/src/index.ts
Woo, a test.  This is still slightly flawed.  But it's better than what we had before (which was nothing)
=> spec: add proper package test for webpack ts template

.gitignore, .vscode/extensions.json, .vscode/settings.json
This is a bit opinionated so happy to leave these gitignored 🤷 
* Adds reccomended workspace extensions for eslint, prettier and mocha
* Configures eslint + prettier to format on save
* Configures mocha so you can run single / debug single tests from the vscode UI (including step by step breakpoints)
=> build: add vscode config for better devxp

packages/publisher/s3/src/PublisherS3.ts
When making with windows.squirrel and the noDelta options selected, the
delta package will end up in the artifacts list and kill the publishing
phase. Although unrelated, this will only publish files that are
actually on disk at the time of publishing.
=> fix(publisher-s3): ensure files are on disk before publishing

packages/maker/squirrel/src/MakerSquirrel.ts, packages/publisher/s3/src/PublisherS3.ts
A better fix for f3d38e0dfbcb307355adfe5b2118ebedbdd91bcc that doesn't just drop all missing files for a single publisher, rather is ensures the maker does not erroneously add the file to the artifacts list in the first place.
=> fix(maker-squirrel): do not register the delta nupkg as an artifact when deltas are disabled

packages/maker/pkg/src/MakerPKG.ts, packages/maker/pkg/test/MakerPKG_spec.ts
Supersedes #2726
there's some weirdness rebasing when pulling from the `master` branch of a fork I don't want to deal with.
=> fix(maker-pkg): add targetArch to pkg name

packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/test/WebpackConfig_spec.ts
Ref https://github.com/electron/forge/issues/1590 and https://github.com/electron/forge/pull/3050#pullrequestreview-1173470995
Removes the DefinePlugin magic variables from the renderer process.
Associated docs change: https://app.gitbook.com/o/-LBKDRmeoAGTb1M5X51f/s/-LBKK1y7h_XWAtuRJG9X-4037718589/~/changes/V3yAgQ9u6bblHPLwO1bj/config/plugins/webpack
=> fix(plugin-webpack): remove define plugin from renderer config

.github/workflows/ci.yml, package.json, tools/test-globber.ts, yarn.lock
Follow-up to https://github.com/electron/forge/pull/3044, this PR removes the Istanbul code coverage tool from our test commands, and de-duplicates the `coverage` and `test` commands.
> **Note**
> There was a discrepancy in how `coverage` and `test` ran fast vs. slow tests.
>
> * `coverage` ran fast tests with the `INTEGRATION_TESTS=0` env var, which specifically disabled the `tests/slow/api_spec_slow.ts` file.
> * `test` ran fast tests with the `TEST_FAST_ONLY` env var, which skips any tests that don't end with `spec.ts`.
>
> I'm not aware of the historical context behind the two flags but it seemed inconsistent to me. I ended up keeping the `TEST_FAST_ONLY` env var in this PR and removing the other one.
=> build(test): remove unnecessary coverage artifacts

packages/maker/pkg/src/Config.ts, packages/maker/pkg/src/MakerPKG.ts
ISSUES CLOSED: #1784
Allow to override `.pkg` filename.
=> feat(maker-pkg): allow to override .pkg name

packages/plugin/webpack/test/fixtures/apps/native-modules/webpack.rules.js, packages/template/webpack-typescript/tmpl/webpack.rules.ts, packages/template/webpack/tmpl/webpack.rules.js
Fixes https://github.com/electron/forge/issues/3055
The reason this plugin does this is long and complicated but it's easy to just not run the plugin on app-code and limit it to `node_modules`.  If you have node_modules code that does this pattern of assuming webpack will make the worker (a) that's weird and (b) you can just exclude that module in a similar way.
This should fix it by default for like 99% of folks though.
=> fix(template-webpack): only run asset relocator loader on `node_modules` folder

package.json, packages/api/core/package.json, packages/api/core/src/util/forge-config.ts, packages/api/core/test/fast/forge-config_spec.ts, packages/api/core/test/fixture/dummy_ts_conf/forge.config.yml, packages/api/core/test/fixture/dummy_ts_conf/package.json, yarn.lock
This PR makes it possible to specify a config file of any extension in the `config.forge` property of `package.json`. While https://github.com/electron/forge/pull/2993 allows for config files in extensions other than .js, they're only interpreted correctly if you don't specify the `config.forge` property in your `package.json` - if you do, the file is interpreted as plain .js.
This seems unexpected and can get on the way if one tries to migrate to, say, a .ts config file just by changing the extension in the `package.json` like this...
```diff
"config": {
-    "forge": "./forge.config.js"
+    "forge": "./forge.config.ts"
},
```
... because Forge expects it to be .js and throws an error. Currently, the entire `config.forge` must be removed for Forge to use the …
=> fix(core): allow the `forge.config` property in `package.json` to point to a non-js file

packages/maker/deb/README.md, packages/maker/flatpak/README.md, packages/maker/rpm/README.md, packages/maker/squirrel/README.md
5104cc0 changed the URLs to internal modules, which broke some links in our generated API docs.
=> docs: fix InternalOptions links in API docs

CONTRIBUTING.md, package.json
We don't leverage our conventional commit usage to help automate versioning.
Wraps the `lerna publish` command into a new `lerna:publish` npm script with additional configuration to address the two issues above.
* `--conventional-commits`: Auto-selects the package number for us.
* `--no-changelog`: Seems like the changelog generated is per package, which we don't want. Let's keep doing this step manually.
Having this in a command within the repo helps in two ways:
1. Less human error possible by forgetting a flag by accident.
2. Lerna version matches our devDependencies rather than being a globally installed NPM package.
I also changed the root `package.json` version number to `0.0.0-development` since Lerna doesn't update the root package.json number by default and our version number was …
=> build: improve lerna publish process

packages/publisher/electron-release-server/src/PublisherERS.ts
- post request form data for version now uses flavor value
- also including auto channel selection for 'rc' versions
=> fix(publisher-ers): properly publish non-default flavours

yarn.lock
One remaining `yarn audit` output will be fixed when https://github.com/doyensec/electronegativity/pull/100 lands and gets rolled in to forge
=> build: update dependencies to clean up yarn audit

.husky/pre-commit
Fix our husky usage with `npm@9`
=> build: npm@9 removed the bin command

packages/api/core/src/util/plugin-interface.ts
Some internal hooks are decorated with the `__hookName` field to indicate that the first parameter should be the task. However, when invoking these callbacks the config param was left out. This resulted in a signature mismatch, which caused issues like #3114 where the arch param was not being passed along correctly to rebuild.
=> fix(core): pass `this.config` when calling internal hooks

packages/api/core/src/api/package.ts
Fixes #3128
For context, we use some pretty ugly hacks for Electron Packager to work with Listr2 (without being written with Listr2 itself).
To make this work, there's a single `packagerPromise` resolving from the `electron-packager` call:
https://github.com/electron/forge/blob/6a118c6c9cbf9b74341f1ff1ce5a311017fdad33/packages/api/core/src/api/package.ts#L307-L313
If this Promise rejects, then we catch it and reject it with an array of reject handlers from all subtasks declared above:
https://github.com/electron/forge/blob/6a118c6c9cbf9b74341f1ff1ce5a311017fdad33/packages/api/core/src/api/package.ts#L177
The problem here is that the `rejects` array is empty in the first `.catch()`, so the error is caught but never propagated. Therefore, the CLI ends up stalling …
=> fix(package): ensure `electron-packager` throws if fails

.github/workflows/ci.yml, package.json, tools/test-globber.ts
… `slow-tests` job
Basically the title. This PR slashes a minute or so (~10%-ish) from the time it takes to run the slow tests by not re-running the fast tests, which are already covered by a separate job.
=> ci: create a `test:slow` script to avoid re-running fast tests in the `slow-tests` job

packages/publisher/electron-release-server/src/PublisherERS.ts, packages/publisher/electron-release-server/test/PublisherERS_spec.ts
Recently, v2.0 of electron-release-server was released. This version updated many of the underlying packages and should be adopted by all users of the server. In the process, the API changed due to a change with SailsJS. This corrects the API usage within the ERS publisher plugin to allow users to continue using it.
Note that this issue was reported here: https://github.com/ArekSredzki/electron-release-server/issues/314
=> fix(publisher-ers): Update ERS API usage for v2.x

packages/maker/rpm/src/MakerRpm.ts, packages/maker/rpm/test/MakerRpm_spec.ts
The canonical name used by the `rpm` package is aarch64. The current behavior of leaving the name arm64 unmapped can lead to subtle behavior differences, since during the RPM building process, the platform name is used for matching against macros under `/usr/lib/rpm/platform/<platform>/macros`, and the platform name there is `aarch64-linux`. Mapping to aarch64 also ensures that the behavior of `--arch=arm64` is the same as running on a Linux Arm64 machine, where `uname` will be returning aarch64, not arm64.
Note that this does change the extension of the final RPM to `*.aarch64.rpm` instead of `*.arm64.rpm`.
=> chore(maker-rpm): map arm64 -> aarch64

.gitignore
This artifact is created when `yarn lerna:publish` fails.
=> chore: gitignore `lerna-debug.log`

CONTRIBUTING.md
Based on learnings from v6.0.5 release.
=> docs: update release process guide

package.json, packages/plugin/fuses/README.md, packages/plugin/fuses/package.json, packages/plugin/fuses/src/FusesPlugin.ts, packages/plugin/fuses/src/util/getElectronExecutablePath.ts, packages/plugin/fuses/test/FusesPlugin_spec_slow.ts, packages/plugin/fuses/test/fixtures/app/forge.config.ts, packages/plugin/fuses/test/fixtures/app/package.json, packages/plugin/fuses/test/fixtures/app/src/main.js
Plugin for [Fuses](https://github.com/electron/fuses).
Closes #3076.
=> feat: add Fuses plugin

packages/api/core/src/api/publish.ts
Fixes a path issue within publisher -> dryRunResume. If a dry run occurred on one platform (e.g. Windows), the path slashes will retain their original formatting, even if the resume action is called on a platform with different path syntax (e.g. Linux).
This PR normalizes the path formats to fix whatever format is needed for dryRunResume.
=> fix: use correct platform paths for artifacts in dryRunResume

packages/maker/zip/package.json, packages/maker/zip/src/Config.ts, packages/maker/zip/src/MakerZIP.ts, packages/maker/zip/test/MakerZip_spec.ts
These two new options allow the zip maker to spit out a valid RELEASES.json file for use with the Electron autoUpdater.  It makes the most sense to put this in the zip maker as the zip artifacts are what the macOS auto updater uses to update.  They are a parallel to the `remoteReleases` option you can pass to the squirrel windows maker.
This is part 1 of a multi-part series of PRs to forge + update-electron-app + forge-docs to make the story for "I use forge, I want to update my app from static storage like S3" incredibly easy to tell.
=> feat(maker-zip): add new macUpdateManifestBaseUrl and macUpdateReleaseNotes options

packages/plugin/vite/src/VitePlugin.ts
Node.js v16+ must check in advance if the directory exists, while v14 works fine 😅
*I developed `@electron/forge-plugin-vite` using the v14 version :(*
=> fix(plugin-vite): start Vite error

packages/plugin/fuses/README.md, packages/plugin/fuses/src/FusesPlugin.ts
Fixing a couple of whoopsies from #3132:
- `resetAdHocDarwinSignature` logic for `platform=mas`
- a _very_ minor typo in the README that is not worth a separate PR IMO.
=> fix(plugin-fuses): `resetAdHocDarwinSignature` rules on Mac

packages/api/core/package.json, packages/plugin/vite/package.json, packages/template/vite/package.json
In 6.1.0, you cannot create a new Vite template with create-electron-app, because we did not include the needed packages in dependencies. This PR adds the needed dependency to @electron-forge/core.
=> chore: add needed Vite infra details

packages/plugin/vite/src/VitePlugin.ts
Use the Vite dev-server close as it also close fs-watcher, hrm-ws, pre-bundle etc.
https://github.com/vitejs/vite/blob/v4.2.0/packages/vite/src/node/server/index.ts#L455-L462
=> fix(plugin-vite): correctly close vite dev-server

packages/publisher/s3/src/PublisherS3.ts
Fixes electron/forge#3166
Simply put, the default behaviour of `@aws-sdk/lib-storage` is to fail silently if part of a file fails to upload to S3, but it includes this option, which makes it actually raise an error. There's a separate PR upstream (https://github.com/aws/aws-sdk-js-v3/pull/4414) to make that behaviour the default.
See also: https://github.com/aws/aws-sdk-js-v3/issues/2311
=> fix(publisher-s3): Make S3 upload fail non-silently

packages/api/core/src/api/publish.ts
Follow up to #3184- this PR re-assigns any incorrect paths back to the makeResults, so that publishers will later handle them correctly.
=> fix: normalize artifact paths in makeResult dryRunResume

packages/template/vite/tmpl/vite.main.config.mjs
Packages like axios have a browser field in package.json. The main process needs to resolve the node module, not the browser module.
Packages like axios have a browser field in package.json.
The main process needs to resolve the node module,
not the browser module.
=> fix(template-vite): ignore `browser` field for isomorphic packages

packages/api/core/src/api/make.ts, packages/maker/base/src/Maker.ts, packages/maker/base/test/config-fetcher_spec.ts, packages/maker/deb/test/MakerDeb_spec.ts, packages/maker/dmg/test/MakerDMG_spec.ts, packages/maker/flatpak/test/MakerFlatpak_spec.ts, packages/maker/pkg/test/MakerPKG_spec.ts, packages/maker/rpm/test/MakerRpm_spec.ts, packages/maker/snap/test/MakerSnap_spec.ts, packages/maker/zip/test/MakerZip_spec.ts
This PR changes the MakerBase `prepareConfig()` function to accept asynchronous callbacks.
=> feat(make): allow async maker configs

packages/publisher/s3/src/PublisherS3.ts
I don't think anyone can viably be using this publisher for multiple arches at the moment without using the `keyResolver` which this change doesn't impact.  There's a world where this breaks someone, but I don't think we make any documented guarantees around _where_ the file gets uploaded too exactly in the bucket (maybe we should document that once this lands?)
=> fix(publisher-s3): ensure published files do not overwrite multiple arches

packages/api/core/src/api/init-scripts/init-npm.ts, packages/template/base/tmpl/forge.config.js, packages/template/webpack-typescript/tmpl/forge.config.ts, packages/template/webpack-typescript/tmpl/package.json, packages/template/webpack/tmpl/forge.config.js
Enables `asar` by default with the AutoUnpackNativesPlugin in all of our templates.
cc @malept @MarshallOfSound
=> feat(template): enable asar by default

packages/api/core/src/util/plugin-interface.ts
This avoids a non-descript `[object Object]` error in our logging.
=> fix(core): properly log invalid plugin configs

packages/plugin/auto-unpack-natives/README.md, packages/template/base/tmpl/forge.config.js, packages/template/webpack/tmpl/forge.config.js
Fixes an issue with the v6.2.0 release where templates were broken.
=> fix(template): add missing config in plugin

.circleci/config.yml
Bumps the versions of several build environment dependencies to get them off deprecated versions:
* Xcode to 14.3.0
* Node to v18 (v16 EOL is Sep 2023)
* Windows Sever to 2022, to pick up a newer `nvm-windows` which fixes issues with newer Node versions
=> ci: bump deprecated versions

packages/publisher/electron-release-server/src/PublisherERS.ts
- [ x ] I have read the [contribution documentation](https://github.com/electron/forge/blob/main/CONTRIBUTING.md) for this project.
- [ x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
- [ x ] The changes are appropriately documented (if applicable).
- [ x ] The changes have sufficient test coverage (if applicable).
- [ x ] The testsuite passes successfully on my local machine (if applicable).
At present, the platform field only supports `osx_64` under OSX, and the judgment branch of `osx_arm64` is missing.
=> fix(publisher-ers): support arm64 osx platform

packages/template/vite/tmpl/vite.main.config.mjs
- [n/a] The changes are appropriately documented (if applicable).
- [n/a] The changes have sufficient test coverage (if applicable).
- [n/a] The testsuite passes successfully on my local machine (if applicable).
In some cases `browserField: false` in the `vite.main.config.js` is not sufficient to ensure that the Node version of a package is bundled (or rather, the browser version is not bundled) - in particular where the package uses [conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports), because Vite's resolver [favours conditions over the browser field](https://vitejs.dev/config/shared-options.html#resolve-mainfields):
> Note this takes lower precedence than conditional exports resolved from the exports field: if an entry …
=> fix(template-vite): incorrectly bundling browser entrypoints

CONTRIBUTING.md, packages/api/core/src/util/forge-config.ts, packages/api/core/test/fast/forge-config_spec.ts, packages/api/core/test/fixture/async_forge_config/forge.config.js, packages/api/core/test/fixture/async_forge_config/package.json
This PR modifies the `getForgeConfig()` method to accept asynchronous configs.
=> feat(package): add support for async Forge configs

.eslintrc.json, .npmignore
After #3284 this file is no longer needed (wasn't being used before anyway). Requires a couple of ESLint config changes as previously there were errors being suppressed by the presence of `.npmignore`
=> build: drop unused .npmignore

packages/api/core/package.json
In order to install a template from the `electron-forge init` command, the template needs to be a dependency of the `@electron-forge/core` package.
Closes https://github.com/electron/forge/issues/3304
See:
```
success Installed "create-electron-app@6.4.0" with binaries:
- create-electron-app
electron-forge:init Initializing in: /Users/erick.zhao/640-test-app +0ms
[STARTED] Locating custom template: "vite-typescript"
electron-forge:init:find-template Trying global template: electron-forge-template-vite-typescript +0ms
electron-forge:init:find-template Error: get-installed-path: module not found "electron-forge-template-vite-typescript" in path /Users/erick.zhao/.nvm/versions/node/v16.20.1/lib/node_modules/electron-forge-template-vite-typescript +1ms …
```
=> fix(cli): add `template-vite-typescript` to Forge's core dependencies

packages/plugin/fuses/test/FusesPlugin_spec_slow.ts, packages/plugin/fuses/test/fixture/app/package.json.tmpl
Now that the Fuses plugin is published to npm, the test app doesn't need to install it from the filesystem anymore. I've also updated the output directory path to make it consistent across all platforms/architectures (this was already implemented [here](https://github.com/electron/forge/blob/3d2e8d40c77f4c456b04b610204e669ec0132434/packages/plugin/fuses/test/fixture/app/forge.config.ts#L14-L16), but it wasn't working because of a bug with the `afterComplete` hook that's been fixed since v6.2.1).
This will hopefully solve that nasty error we've been getting when running this test locally 🤞🏼
=> test(plugin-fuses): clear test TODOs

package.json
I don't think anyone on the Forge dev
team uses Volta anymore.
=> chore: remove Volta config

package.json, packages/plugin/webpack/package.json, packages/plugin/webpack/src/util/AssetRelocatorPatch.ts, packages/plugin/webpack/test/AssetRelocatorPatch_spec.ts, yarn.lock
upgrade the dependency- upstream has merged their version of https://github.com/jantimon/html-webpack-plugin/pull/1650/files and https://github.com/jantimon/html-webpack-plugin/pull/1763
This allows us to stop using a small hack where we call dirname(__filename) instead of __dirname
=> build(deps-dev): upgrade html-webpack-plugin to 5.5.3

.circleci/config.yml, .gitignore, .mocharc.js, package.json, yarn.lock
This PR uses the `store_test_results` step in our CircleCI config. To collect test results, I added the [`mocha-junit-reporter`](https://www.npmjs.com/package/mocha-junit-reporter) package. This reporter will run when `process.env.CI` is true.
This is a pre-requisite for using Circle's "split by timing" test parallelism feature: https://circleci.com/docs/parallelism-faster-jobs/
This PR follows the [Collect Test Data](https://circleci.com/docs/collect-test-data/) doc from CircleCI.
=> build: add circleci test reporting

.circleci/config.yml, .mocharc.js
Follow-up to #3316
Test timings are still busted, so I followed CircleCI's troubleshooting docs here: https://support.circleci.com/hc/en-us/articles/360021624194-Test-Summary-Troubleshooting
Two things that we weren't respecting:
* XML reports need to go inside a subfolder of the main test summary folder.
* Paths need to match the output of the test glob from the `circleci` CLI. This means that we need to convert the output strings from `mocha-junit-reporter` from absolute paths to relative paths.
=> ci: junit reporter adjustments

.github/workflows/add-to-project.yml
Necessary so PRs from forks get the creds secret. This is safe because this workflow does not do anything with the contents from the PR.
=> ci: use pull_request_target in add to project workflow

.circleci/config.yml
I don't think the cache step is doing anything, unfortunately.
=> ci: disable node_modules cache

packages/maker/squirrel/README.md
Doesn't work on macOS so let's not lead folks astray.
=> docs: maker-squirrel does not support macOS

packages/plugin/webpack/src/Config.ts, packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/src/WebpackPlugin.ts, packages/plugin/webpack/src/util/EntryPointPreloadPlugin.ts
fixes: https://github.com/electron/forge/issues/3343
Due to webpack preload [refactoring](https://github.com/electron/forge/pull/3101), a bug mainly affecting windows resulted in users temporarily seeing an error as the window attempted to display preload contents before webpack was done compiling the preload. This PR introduces logic to wait for preload compilation to finish first.
=> fix(plugin-webpack): preload race condition

packages/publisher/github/src/Config.ts, packages/publisher/github/src/PublisherGithub.ts, packages/publisher/github/src/util/github.ts, packages/publisher/github/test/github_spec.ts
This PR includes fixes related to `publisher-gihub`:
* Replace special characters in the asset name https://github.com/electron-userland/electron-forge/issues/1759
* Allow to override existing asset of release https://github.com/electron-userland/electron-forge/issues/1760
=> feat(publisher-github): assets management

packages/plugin/fuses/src/util/getElectronExecutablePath.ts
We're using the host platform instead of the target platform to get the binary path, which results in an incorrect path when making for a different platform (like `/path/to/electron.exe` instead of `/path/to/electron` when making for Linux on Windows).
=> fix(plugin-fuses): use target platform in the executable path

.github/workflows/gh-pages.yml
Move to using a GitHub app to do the commits for GH pages deploys.
=> ci: use GitHub app for commits

CONTRIBUTING.md
=> docs: updated contributing.md

packages/publisher/github/src/PublisherGithub.ts
Fixing a misleading error message I came across in https://github.com/electron/forge/issues/3392
=> fix(publisher-github): update error message to reflect the correct property names

package.json
For folks using the Corepack feature in Node.js, `packageManager` specifies which package manager version to use. Not sure if we want to land this right away since the feature isn't marked as stable in Node.js yet, but people using Corepack with the `--activate` (global fallback version) flag might be installing the wrong version of Yarn.
ref https://github.com/electron/forge/pull/3357#issuecomment-1725870363
Note: this feature is still marked as experimental. See https://github.com/nodejs/corepack/issues/104 for discussion of stability.
=> chore: specify `packageManager` in package.json

packages/maker/dmg/src/Config.ts
This PR updates the `DMGContents` interface to align with the [appdmg](https://github.com/LinusU/node-appdmg#specification) dependency, where the `name` property is optional.
=> fix(maker-dmg): make 'name' optional in DMGContents interface

.eslintignore, packages/api/core/helper/dynamic-import.d.ts, packages/api/core/helper/dynamic-import.js, packages/api/core/package.json, packages/api/core/src/util/forge-config.ts, packages/api/core/test/fast/forge-config_spec.ts, packages/api/core/test/fixture/dummy_default_esm_conf/forge.config.js, packages/api/core/test/fixture/dummy_default_esm_conf/package.json
This tiny PR adds ESM config support. Test added. Closes https://github.com/electron/forge/issues/3350
It is not a breaking change. Be ready for Electron 28 with ESM support! 💯
=> feat: esm forge.config.js support

packages/api/core/package.json, packages/api/core/src/api/import.ts, packages/api/core/src/api/make.ts, packages/api/core/src/api/package.ts, packages/api/core/src/api/publish.ts, packages/api/core/src/api/start.ts, packages/api/core/src/util/hook.ts, packages/api/core/src/util/plugin-interface.ts, packages/api/core/test/fast/publish_spec.ts, packages/utils/tracer/package.json, packages/utils/tracer/src/index.ts, packages/utils/types/src/index.ts, yarn.lock
Please review this diff with whitespace disabled 🙇 
This is kinda ready but also kinda a WIP, this adds all the tracing but no flags for actually getting the trace output.  Just want folks thoughts on the approach
The idea here is the sub ecosystem modules + makers + publishers + plugins will also call into `@electron-forge/tracer`
=> feat: add tracing support for forge API

packages/api/cli/src/util/check-system.ts
Explicitly disallows Yarn 2 and drops support for Yarn 0.x.
This is technically a breaking change, but according to npm's download stats, Yarn 0.x only has 2000 installs (~0.08%) of `yarn` (<=1.x) installs in the last week.
=> chore(cli): limit yarn@^1.0.0

packages/maker/zip/src/MakerZIP.ts, packages/maker/zip/test/MakerZip_spec.ts
=> fix: handle missing manifest in zip maker

packages/template/webpack-typescript/tmpl/webpack.main.config.ts
This PR modifies the the `webpack-typescript` template to enable type-checking in the main webpack config, rather than just the renderer's webpack config. Without this change, Typescript compile errors in both the renderer and main process Typescript files did not appear to get printed anywhere at all. @MarshallOfSound did you verify that type-checking worked in the original version of the `typescript-webpack` template?
With this change, Typescript errors in either the renderer or main process source code get printed to the console that `npm start` is launched from.
=> fix(template-webpack-typescript): use fork-ts-checker-webpack-plugin in main webpack config

package.json
fast follow-up to a typo in #3359
=> chore: fix sha1 for `packageManager`

.github/workflows/gh-pages.yml
We forgot to publish docs for v7 tags and need to catch up.
=> ci: allow manual API documentation publish

CONTRIBUTING.md, package.json, yarn.lock
Following the v7.1.0 release notes today, it's nice to have this available.
=> docs: add notes on publishing a new monorepo package

packages/publisher/base-static/package.json, packages/publisher/base-static/src/PublisherStatic.ts, packages/publisher/base-static/test/StaticPublisher_spec.ts, packages/publisher/gcs/package.json, packages/publisher/gcs/src/PublisherGCS.ts, packages/publisher/s3/package.json, packages/publisher/s3/src/PublisherS3.ts
Bit of some fancy class inheritance stuff going on here 😆 But basically all to dedupe the key resolver logic for the two static publishers we have and I guess all future ones we add / others want to make
=> refactor: dedupe key resolver for static publishers

packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/test/WebpackConfig_spec.ts, packages/plugin/webpack/test/fixtures/main_config_external/mainConfig.module.js
Although you can do `./webpack.main.config.ts` currently you still have to do `module.exports = config` instead of `export default config`.  This handles the default export in the same way that our forge config resolver does
=> fix: handle webpack configs exported as default

packages/plugin/webpack/src/WebpackConfig.ts, packages/plugin/webpack/test/WebpackConfig_spec.ts
This avoids an error in packaged apps "Automatic publicPath is not supported in this browser".  This is only emitted by sandboxed preload scripts as I guess they struggle to realize they're in a browser 😆
=> fix: set empty publicPath for preload scripts

packages/publisher/electron-release-server/src/PublisherERS.ts, packages/publisher/electron-release-server/test/PublisherERS_spec.ts
Issue: https://github.com/electron/forge/issues/3430
Electron Release Server, specifically the Sails blueprint, only allows a maximum of 30 records to be returned on the endpoint **/api/version**. The problem with this is when you call:
`const versions: ERSVersion[] = await (await authFetch('api/version')).json();
`
You get back a random 30 records. If you have 30 or more versions that have been created, this poses a problem. If you don't get the version that you are creating, say, **0.0.1_stable**, on that **/api/version** call, it will try to create it again even though it's already been created in the database. It will result in the error:
`Error: ERS publish failed with status code: 400 (*** /api/version)
`
If you look at the Electron Release Server error, …
=> fix(electron-release-publisher): change api/version endpoint in PublisherERS to use versions/sorted

packages/plugin/base/src/Plugin.ts, packages/plugin/webpack/package.json, packages/plugin/webpack/src/WebpackPlugin.ts, packages/utils/core-utils/src/rebuild.ts, packages/utils/types/src/index.ts, yarn.lock
Fixes #3436
This is a follow up to #3433 that optimizes the build to only run webpack once and instead generate a hash<->path mapping between native modules and their respective paths on disk.
This handles:
* Multiple native modules having the same hash
* Modules not being mappable
This might fall apart:
* If the same native module built for different arches ends up in a different place on disk (this probably isn't compatible with webpack anyway, so probs all good here)
Example:
=> refactor: only run webpack once for multi-arch packages

packages/plugin/webpack/src/WebpackPlugin.ts
=> fix: actually depend on preceeding groups

packages/maker/appx/src/MakerAppX.ts, packages/maker/base/src/Maker.ts, packages/maker/base/test/version_spec.ts
According to [semver2](https://semver.org/), a version can consist of a build part denoted by a `+` sign. The current implementation of `normalizeWindowsVersion` does not take that into account. Although the `+` sign usually comes after a `-` sign, it is not always the case. `normalizeWindowsVersion` should also handle the case where only `+` but not `-` exists.
=> fix: normalize windows version with build part correctly

.vscode/settings.json
Visual Studio Code 1.85 automatically changes `settings.json` on open as `true` is no longer a valid setting.
See [vscode-workspace-settings-change-on-its-own](https://stackoverflow.com/questions/77637621/vscode-workspace-settings-change-on-its-own) and microsoft/vscode-eslint#1750 @dbaeumer
#3456
=> fix: .vscode settings.json changes on open

packages/api/core/src/util/resolve-dir.ts
If use programmatic usage instead of CLI, the 'package.json' wont be found in this function
=> fix(core): packageJSON won't be found when programmatic usage instead of CLI

packages/template/base/tmpl/forge.config.js, packages/template/base/tmpl/package.json, packages/template/vite-typescript/tmpl/forge.config.ts, packages/template/vite-typescript/tmpl/package.json, packages/template/vite/tmpl/forge.config.js, packages/template/vite/tmpl/package.json, packages/template/webpack-typescript/tmpl/forge.config.ts, packages/template/webpack-typescript/tmpl/package.json, packages/template/webpack/tmpl/forge.config.js
In order to make fuses more discoverable and add safe defaults for new electron applications, we are introducing a default fuses configuration in each of the existing templates used in electron forge init
To test this change, I created a new project using our 5 existing templates: base, vite, vite-typescript, webpack, webpack-typescript. For each of these projects, I ran `yarn package` and checked that the resulting .app ran as expected. I also verified that the fuses were actually set by running `npx @electron/fuses read` and verifying that the output matches the forge.config configurations:
```
Fuse Version: v1
RunAsNode is Disabled
EnableCookieEncryption is Enabled
EnableNodeOptionsEnvironmentVariable is Disabled
EnableNodeCliInspectArguments is Disabled …
```
=> feat: adds default fuses to templates

packages/publisher/github/src/Config.ts, packages/publisher/github/src/PublisherGithub.ts
Exposes a config option to automatically generate the release notes when creating the GitHub release.
=> feat(publisher-github): option to automatically generate release notes

packages/plugin/electronegativity/src/ElectronegativityPlugin.ts
- `isRelative` should be `boolean` and defaults to `false`.
- `parserPlugins` should be optional.
=> chore(plugins/electronegativity): correct some config types 

package.json
The push API documentation workflow is [running out of memory](https://github.com/electron/forge/actions/runs/7993414416/job/21829876738) on new releases (both v7.2.0 and v7.3.0 failed).
@erickzhao will try to look into improving the overall process in the future, but in the meantime the quickest way to mitigate the issue is to bump the memory limit.
=> build: bump memory limit for docs:generate script

packages/publisher/github/package.json, packages/publisher/github/src/PublisherGithub.ts, packages/publisher/github/src/util/github.ts, packages/publisher/github/test/github_spec.ts
Partially reverts #1761, which was really an undocumented breaking change since it sometimes changes the artifact names being uploaded to GitHub. That caused links to break on the website for Fiddle releases.
Rationale for reverting the change:
* It was a breaking change
* Renaming artifacts at publish time could cause problems when existing output depends on those names (e.g. `RELEASES`)
* We'll likely always be diverged from GitHub's actual filename sanitation algorithm, and any time we update ours to better match, it's technically a breaking change for Forge
* Since we might be diverged, there's the possibility that the filename will be changed twice (once on our side, and again on GitHub's side) - this was true for the existing code as GitHub doesn't allow …
=> fix(publisher-github): don't sanitize asset names before upload

package.json, yarn.lock
Not sure why this happens, but easy enough to fix with no impact to published modules by adding this types package to our root package json.
=> build: fix keyv type resolution warning during dev

.circleci/config.yml
Fixes our current CI issues.
Looks like WiX3 just got its first package release in 5 years, which fixes a bunch of security problems.
See https://github.com/wixtoolset/wix3/releases/tag/wix314rtm
> WiX v3.14 is the latest recommended maintenance release of WiX v3; it contains mitigations in all versions of WiX v3 for a vulnerability affecting all bundles. We recommend upgrading to WiX v3.14--or WiX v4.0--as soon as possible.
> For more information about the vulnerability, see [WiX Security Releases Available](https://www.firegiant.com/blog/2024/2/6/wix-security-releases-available/).
=> ci(windows): pin version of wix toolset to v3.14.0

package.json, packages/api/core/package.json, packages/api/core/test/slow/api_spec_slow.ts, packages/maker/squirrel/package.json, packages/maker/wix/package.json, packages/plugin/vite/package.json, packages/plugin/webpack/package.json, packages/utils/types/package.json, yarn.lock
Updating all dependencies which now use `@electron/windows-sign`. This is a non-breaking change.
=> chore: Bump @electron/windows-sign deps

packages/template/base/tmpl/index.js
This PR:
- Uses `app.whenReady().then(...)` instead of `app.on('ready', ...)` to better handle edge cases
- Moves `activate` listener inside existing `whenReady` callback as outlined in the[ docs](https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app#open-a-window-if-none-are-open-macos) so that it only happens after app is initialized
- Add node prefix with path module in import to support [current best practice](https://github.com/electron/electron/pull/39681).
=> docs: update forge create-electron-app template to match tutorial

.github/workflows/gh-pages.yml
Switches the docs publishing workflow to using `malept/github-action-gh-pages` to align across the org (with `electron/get` and `electron/packager`), and uses `dsanders11/github-app-commit-action` to sign the commit.
=> ci: make signed commits when publishing docs

package.json, packages/api/core/package.json, packages/plugin/vite/package.json, packages/plugin/webpack/package.json, packages/utils/types/package.json, yarn.lock
This isn't really required because transitive deps can be updated without having to update them in forge, but I'm writing a doc that says "this works in packager X and forge Y" and the only way to be sure that sentence is correct is to make a version of forge that forces packager X 😆
=> fix: bump packager minimum dep

.github/workflows/gh-pages.yml
This got flipped on in #3520 because I thought it would be nice, but [the workflow is now hitting GitHub server errors](https://github.com/electron/forge/actions/runs/8759922305/attempts/2) and I suspect it has to do with the number of files changed. Removing `versionDocs: true` should cut down on the number of files changed and hopefully let the workflow succeed.
=> ci: don't use versionDocs option in API Documentation workflow

packages/api/core/test/slow/api_spec_slow.ts
Changes our `import` test so that we clone `electron-quick-start` and make sure that the `package` command works. I'm also not sure what the original assertion was actually testing.
Would prevent regressions such as https://github.com/electron/forge/issues/3509.
=> test(import): check if electron-quick-start packages

packages/maker/squirrel/src/MakerSquirrel.ts
The logic here I think is wrong. It adds the `-delta` file to `artifacts` even if it doesn't exist. This will cause `--from-dry-run` to fail. I think electron installer might not always produce a delta file.
Given the logic below for the `msi` that check the file exists before adding it, that made sense to do here to.
=> fix(maker-squirrel): only push `delta` artifacts if they exist on disk

yarn.lock
We fixed a symlink bug in `@electron/asar@3.2.10` and also this de-duplicates the 3 copies of asar we're installing in the lockfile.
=> chore: bump `asar` dep to latest

package.json, packages/maker/dmg/package.json, packages/maker/dmg/src/Config.ts, packages/maker/dmg/src/MakerDMG.ts, packages/maker/dmg/test/MakerDMG_spec.ts, yarn.lock
Upgrades to the latest `electron-installer-dmg` release, which provides native TS types so we don't need to duplicate the configuration within Forge.
=> build: upgrade `electron-installer-dmg@5`

packages/plugin/webpack/src/WebpackConfig.ts
If you have opened your dev server with https via the `devServer.server` setting, make it aware of it.
=> fix(plugin-webpack): protocol recognizes webpack's `devServer` setting

packages/utils/types/src/index.ts
The previous type here wouldn't work unless you explicitly returned `undefined` within your hook.
=> fix(hooks): allow mutating hooks to have a `void` return

packages/publisher/gcs/src/Config.ts, packages/publisher/gcs/src/PublisherGCS.ts
Optionally pass metadata to GCS objects
Useful for setting cacheControl on files such as RELEASE.json
=> feat: Adding optional metadata config to gcs publisher

packages/maker/wix/src/Config.ts
See here for documentation https://js.electronforge.io/classes/_electron_forge_maker_wix.InternalOptions.MSICreator.html#associateExtensions
Adding to the `MakerWixConfig` interface property `associateExtensions` that allows one to specify exts to be associated with the app icon.
=> feat(maker-wix): Expose the property associateExtensions

packages/api/core/src/util/forge-config.ts, packages/api/core/src/util/index.ts, packages/api/core/src/util/resolve-dir.ts, packages/api/core/test/fast/forge-config_spec.ts, packages/api/core/test/fast/resolve-dir_spec.ts
Fixes: https://github.com/electron/forge/issues/3510
Currently it is not possible to provide a forge config through the API of @electron-forge/core.
This makes integrating electron forge in to other build systems difficult, if these build systems want to provide the configuration for electron forge (for example by using metadata from previous build steps).
This pull request implements two functions ```utils.registerForgeConfigForDirectory(dir: string, config: ForgeConfig): void``` and ```unregisterForgeConfigForDirectory(dir: string): void``` to make this easier.
A "virtual" config registered through the first method behaves as if a forge.config.js file where present at that location exporting the object provided by the config parameter.
This takes precedence over any existing config …
=> feat(core): adding register/unregisterForgeConfigForDirectory to utils

lerna.json, nx.json, package.json, yarn.lock
We're still 1 major version behind, but this brings us 1 step closer :)
Running `npx lerna repair` fixed the configs for v7.
Unfortunately, I didn't have a way to test the publish command before submitting this PR because `lerna publish` does not have a `--dry-run` flag.
=> build(deps): lerna@7

packages/api/core/helper/dynamic-import.d.ts, packages/api/core/helper/dynamic-import.js, packages/api/core/src/api/init-scripts/find-template.ts, packages/api/core/src/api/make.ts, packages/api/core/src/api/package.ts, packages/api/core/src/api/publish.ts, packages/api/core/src/util/forge-config.ts, packages/api/core/src/util/import-search.ts, packages/api/core/src/util/plugin-interface.ts, packages/api/core/test/fast/import-search_spec.ts, packages/api/core/test/fast/publish_spec.ts, packages/api/core/test/fast/require-search_spec.ts
This PR focuses on bringing the initial support loading Forge modules (plugins, makers, publishers etc.) that use ESM for their module format. It should also contain some cosmetic changes like rename of `require-search` to `import-search` (to reflect it isn't around the `require` API only anymore), improvements around the helper so it won't resolve path for modules passed by their names and introduces new function, `dynamicImportMaybe`, that will also try doing `require` first and falling back to ESM when it fails (I chose to `require` first so I won't have to resolve `default` in CJS import).
The main motivation on that is to allow third-parties as well as official Forge modules to be able to effortlessly utilise the ESM syntax entirely. While this is possible for now with the Forge as …
=> feat(core): support ESM Forge module loading

package.json, packages/publisher/s3/package.json, yarn.lock
* Bump for `fast-xml-parser` Dependabot warning
* (`@aws-sdk/abort-controller` is no longer a peer dependency: https://github.com/electron/forge/commit/0a4fed79d766f9f8e16dad811a2b8da12b7b1292
=> chore(publisher-s3): update aws-sdk deps

packages/plugin/vite/README.md
Following a discussion among maintainers, this PR adds documentation to flag the Vite plug-in as experimental, as it is under active development and may introduce unplanned breaking changes.
While we will strive to keep breaking changes to a minimum, this marking allows users to make a more informed decision on risk before using the Vite plug-in for their projects.
=> docs: mark plugin-vite as experimental

package.json, yarn.lock
I believe this fixes https://github.com/electron/forge/security/dependabot/56
Did not update to syncpack 12 because it changed its CLI config around and upgrading wasn't just a simple version bump.
=> build(deps): upgrade syncpack@11

package.json, packages/api/core/package.json, packages/utils/core-utils/package.json, packages/utils/types/package.json, yarn.lock
This PR updates our version of `@electron/rebuild`. The biggest change here can be found in this PR: https://github.com/electron/rebuild/pull/1157
fix: Bump @electron/rebuild to ^3.7.0, which upgrades the internally used version of `node-gyp` to v10 - fixing, among other things, build errors on macOS Sequoia.
=> fix: Bump @electron/rebuild to ^3.7.0

packages/api/core/src/api/make.ts
If a `postMake` hook moves file around we shouldn't log the old wrong location. Using `JSON.stringify` to handle mutation instead of mapping in the hook.
=> fix: log correct directory when hook moves artifacts

.circleci/config.yml
The CI job for slow tests on Linux has started consistently failing, and it looks to be due to OOM. Bumping the resource class size to work around it.
=> ci: use larger Linux resource class for slow tests

packages/api/core/src/api/start.ts, packages/plugin/local-electron/src/LocalElectronPlugin.ts, packages/plugin/local-electron/test/LocalElectronPlugin_spec.ts, packages/plugin/vite/src/VitePlugin.ts, packages/plugin/webpack/src/WebpackPlugin.ts, packages/utils/types/src/index.ts
We already had `postStart` so this is pretty chill 🤷 Removes the "only one thing can mess with start logic" restriction for our own plugins.
=> feat: add preStart hook and port existing startLogic impls

packages/template/base/tmpl/index.js, packages/template/vite-typescript/tmpl/forge.env.d.ts, packages/template/vite-typescript/tmpl/main.ts, packages/template/vite/src/ViteTemplate.ts, packages/template/vite/test/ViteTemplate_spec.ts, packages/template/vite/tmpl/forge.env.d.ts
Closes #3714
Since we removed the copy `dependencies` logic in vite-plugin of `v7.5.0`, this will cause `if (require('electron-squirrel-startup'))` to fail to load.
This is because Vite's built-in `@rollup/plugin-commonjs` cannot handle CommonJS's `require()` function like Webpack in many cases. We need to make some compromises in code writing and try to use ESModule's `import` statement to avoid this problem.
> If anyone wants to know more about this issue, I wrote an article introducing the problem of Vite building CommonJS format code. 👉🏻 https://github.com/vite-plugin/vite-plugin-commonjs/blob/main/commonjs.zh-CN.md
=> fix(vite-template): fix vite template start failed after package

packages/publisher/s3/src/Config.ts, packages/publisher/s3/src/PublisherS3.ts
This allows the caller to omit the ACL from the upload request, per Amazon's recommendation of using bucket owner-enforced permissions.
AWS recommends disabling the use of ACLs and instead using bucket owner-enforced permissions (see https://docs.aws.amazon.com/AmazonS3/latest/userguide/ensure-object-ownership.html). The current configuration and implementation of the S3 publisher always applies an ACL, which simply doesn't work with buckets configured this way. This PR adds an `omitAcl` option to the config that simply omits the ACL from the upload command.
I considered making this config look more like the Google Cloud Storage publisher (which uses essentially applies some of its options, such as `predefinedAcl`, `public`, and `private`, directly to its …
=> feat(publisher-s3): allow ACL omission

packages/plugin/vite/src/ViteConfig.ts, packages/plugin/vite/src/config/vite.main.config.ts, packages/plugin/vite/src/config/vite.preload.config.ts, packages/plugin/vite/src/config/vite.renderer.config.ts
=> fix(plugin-vite): merge Vite `build.lib` config

packages/api/core/test/slow/api_spec_slow.ts
Small improvement for tests. We removed the `forge install` command in a v6 beta, but this test fixture still used `proxyquire` to stub that module.
Eliminating `proxyquire` here also improves type safety as `forge` was previously an `any` type.
=> test: avoid `proxyquire` in `api_spec_slow`

packages/plugin/vite/src/config/vite.base.config.ts
Small edit to vite plugin to allow VitePluginRendererConfig entries to have hyphens in their name.
Motivation is we have a large forge repo with multiple applications / frontends. We have them organized as follows:
.
└── src/
├── app-1-frontend-1
├── app-2-frontend-1
├── app-2-frontend-2
└── app-3-frontend-1
In forge v7.4.0, vite.base.config.ts was a part of the vite-typescript template. Ran into the issue while trying to update our dependencies as a result of #3583. This shouldn't break any existing users as if they already had "-" in their name, the build would've already been failing
=> build(plugin-vite): allow renderer name to contain dashes

packages/api/core/src/util/install-dependencies.ts, packages/api/core/test/fast/install-dependencies_spec.ts
Small refactor fix. `--save` is the default behaviour for package manager install nowadays, so this PR removes the `--save` flag from `npm install` when installing dependencies. This aligns with behaviour with `yarn`.
=> fix(core-utils): don't add --save flag for npm install

packages/plugin/auto-unpack-natives/src/AutoUnpackNativesPlugin.ts
fixed https://github.com/electron/forge/issues/3792
=> fix: update native module unpack pattern to include hidden directories

.circleci/config.yml
We're getting `Job failed due to excessive parallelism` errors in CI now due to this flag.
Closes #3536
=> ci: disable parallelism

package.json
SHA fetched using new `corepack up` command.
ref https://github.com/electron/forge/pull/3359
=> chore: upgrade yarn@1.22.22 in corepack

.github/workflows/gh-pages.yml
`ubuntu-20.04` is deprecated and [will have brownouts in March before sunset in April](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/), so switch to `ubuntu-latest.`
=> ci: change gh-pages workflow to ubuntu-latest runner

package.json, packages/api/cli/src/util/check-system.ts, packages/api/core/package.json, packages/api/core/spec/fast/util/install-dependencies.spec.ts, packages/api/core/src/api/import.ts, packages/api/core/src/api/init-scripts/init-link.ts, packages/api/core/src/api/init-scripts/init-npm.ts, packages/api/core/src/api/init.ts, packages/api/core/src/util/install-dependencies.ts, packages/utils/core-utils/package.json, packages/utils/core-utils/spec/yarn-or-npm.spec.ts, packages/utils/core-utils/src/electron-version.ts, packages/utils/core-utils/src/yarn-or-npm.ts, typings/yarn-or-npm/index.d.ts, yarn.lock
ref https://github.com/electron/forge/issues/2633
Splitting this off from https://github.com/electron/forge/pull/3574 because this is probably easier to land and review in chunks.
=> refactor(core): replace `yarn-or-npm` with `detect-package-manager`

package.json, packages/api/cli/package.json, packages/api/core/package.json, packages/maker/appx/package.json, packages/maker/base/package.json, packages/maker/deb/package.json, packages/maker/dmg/package.json, packages/maker/flatpak/package.json, packages/maker/pkg/package.json, packages/maker/rpm/package.json, packages/maker/snap/package.json, packages/maker/wix/package.json, packages/maker/zip/package.json, packages/plugin/local-electron/package.json, packages/plugin/vite/package.json, packages/plugin/webpack/package.json, packages/publisher/base-static/package.json, packages/publisher/base/package.json, packages/publisher/electron-release-server/package.json, packages/publisher/github/package.json, packages/template/base/package.json, packages/template/vite-typescript/package.json, packages/template/vite/package.json, packages/template/webpack-typescript/package.json, packages/template/webpack/package.json, packages/utils/core-utils/package.json, packages/utils/core-utils/spec/yarn-or-npm.spec.ts, yarn.lock
Vitest released a new major version soon after we merged in our migration PRs. Thankfully, this seems to be a pretty painless migration.
I left a few dangling promises in #3813 that have been fixed in `packages/utils/core-utils/spec/yarn-or-npm.spec.ts`.
=> test: Vitest 3

packages/template/base/src/BaseTemplate.ts, packages/template/vite/src/ViteTemplate.ts, packages/template/vite/tmpl/index.js
Fixes https://github.com/electron/forge/issues/3806
I believe there was an issue that was requiring us to use esm-style imports with the Vite template on Windows, but the initial PR also changed up the base template, which _didn't_ accept this syntax.
=> fix(template): use esm imports for vite template only

packages/api/core/spec/fixture/custom_init/index.js, packages/api/core/src/util/install-dependencies.ts, packages/template/base/src/BaseTemplate.ts, packages/template/base/tmpl/package.json, packages/template/vite-typescript/tmpl/package.json, packages/template/vite/tmpl/package.json, packages/template/webpack-typescript/tmpl/package.json
In https://github.com/electron/forge/pull/3480, we added the `@electron/fuses` plugin to our templates.
This was done by adding the dependencies directly into the `tmpl/package.json` file for each template like so:
https://github.com/electron/forge/blob/71eb328cae06d445e18dde9e9d54c7f4c282c67b/packages/template/base/tmpl/package.json#L13-L16
This approach eventually caused two problems:
1. The `import` command didn't install the correct Fuses dependency (ref https://github.com/electron/forge/issues/3509)
2. The `init` script was hard-coding the version to `^7.2.0` instead of matching the current Electron Forge version.
The first bug was fixed by https://github.com/electron/forge/pull/3535, which added both `@electron/fuses` and `@electron-forge/plugin-fuses` to the base dependencies we …
=> fix(template-base): install correct version of plugin-fuses

packages/api/core/src/api/init.ts, packages/template/vite/src/ViteTemplate.ts, packages/utils/types/src/index.ts
Fixes #3783
We were calling `fs.moveSync(src, dest)` from the template code, but this function fails if `dest` already exists without passing the `overwrite` flag.
To fix this, we align the `overwrite` flag with the value of `--force` being passed into the `init` command.
=> fix(template-vite): make `--force` flag work

.github/workflows/stale.yml
Our issue tracker is slowly getting larger. This PR implements [actions/stale](https://github.com/actions/stale) to close out issues that have [`blocked/needs-repro`](https://github.com/electron/forge/issues?q=is%3Aissue%20state%3Aopen%20label%3Ablocked%2Fneeds-repro) or [`blocked/needs-info`](https://github.com/electron/forge/issues?q=is%3Aissue%20state%3Aopen%20label%3Ablocked%2Fneeds-info) labels if they haven't gotten a response within 14 days.
If an answer is given within 14 days, then the `blocked/` label is removed and the maintainer will need to re-triage.
=> chore: add `actions/stale` for issues

packages/api/core/src/api/package.ts
Fixes https://github.com/electron/forge/issues/3540
Note that these logs _will_ show up at the bottom after execution because we use Listr2 for the Forge CLI. The workaround is to use set `DEBUG` to anything or to set `CI=true` to use the Listr2 fallback renderer.
ref: https://github.com/electron/forge/issues/3796#issuecomment-2574552674
=> fix(package): make `packagerConfig.quiet` configurable

package.json
follow-up to https://github.com/electron/forge/pull/3811
Should make our pre-commit hooks faster.
=> chore: run ESLint with cache on lint-staged

packages/maker/flatpak/src/MakerFlatpak.ts
Hi,
this PR is a fix for the issue described in #3838
It fixes it by adding translating the "arm64" architecture string from electron-forge, into "aarch64", which is what Flatpak is actually expecting.
The same thing was done for "x64" and "x86_64" as well.
closes #3838
=> fix(maker-flatpak): fix flatpakArch for arm64

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Uses `type` instead of `label` for the top-level field. Uses `placeholder` field where applicable and updates some version numbers.
=> chore: clean up issue templates

packages/api/cli/src/electron-forge-init.ts
```
Usage: electron-forge-init [options] [name]
Options:
-V, --version          Output the current version
-t, --template [name]  Name of the Forge template to use
-c, --copy-ci-files    Whether to copy the templated CI files (defaults to false) (default: false)
-f, --force            Whether to overwrite an existing directory (defaults to false) (default: false)
-h, --help             Output usage information
```
It looks like `commander` already shows the default information, so we shouldn't print it twice.
=> fix(cli): deduplicate default information

packages/api/cli/src/electron-forge.ts
Instead of running the system check on every `electron-forge` CLI run, this PR instead skips it by default if no command is run or if the `--help` option is triggered on a command.
This is inspired by @CodeWitchBella's comment in https://github.com/electron/forge/issues/3313, which I'm reading almost 2 years late (sorry 🙇).
> Sidenote: I'd argue that this check should not run at all for things like --version or --help to make debugging a bit less painful. Also, the message references git and node.js when the issue is with yarn version.
=> perf(cli): only check system on commands

package.json, packages/api/cli/package.json, packages/api/cli/src/electron-forge-import.ts, packages/api/cli/src/electron-forge-init.ts, packages/api/cli/src/electron-forge-make.ts, packages/api/cli/src/electron-forge-package.ts, packages/api/cli/src/electron-forge-publish.ts, packages/api/cli/src/electron-forge-start.ts, packages/api/cli/src/electron-forge.ts, tsconfig.base.json, yarn.lock
This PR bumps up our version of `commander`, which is woefully out of date. The motivation here is to reduce friction to make further improvements to our CLI, since commander's API has changed a lot in the last few years.
Note that `commander@11` was the latest major version that supports Node 16, while 13 is the current latest major version.
This migration was done by reading the [CHANGELOG.md](https://github.com/tj/commander.js/blob/master/CHANGELOG.md) for `commander` and ensuring that everything compiled in TypeScript.
Here's a brief explanation of all the changes.
The main `program` object is now a named export.
```diff
- import program from 'commander';
+ import { program } from 'commander';
```
Options for each command are now accessed via the `program.opts()` function rather than …
=> fix: upgrade `commander` 4 -> 11

packages/api/core/src/api/package.ts
Fast follow-up to https://github.com/electron/forge/pull/3831
The default value should still be `quiet: true` even if we let users configure it.
=> fix(package): revert `quiet` default value

packages/api/cli/src/electron-forge.ts, packages/api/cli/src/util/check-system.ts
Fixes #3849
```
> npm install -g yarn@0.28.4
npm warn deprecated yarn@0.28.4: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
changed 1 package in 848ms
> yarn start
yarn start v0.28.4
$ electron-forge start
❯ Checking your system
✖ Checking node version
✖ Incompatible version of yarn detected: "0.28.4" must be in range >= 1.0.0
error Command failed with exit code 1.
```
=> fix(cli): error if system check fails

packages/maker/wix/package.json, packages/maker/wix/src/Config.ts, packages/maker/wix/src/MakerWix.ts
- Fix: https://github.com/electron/forge/issues/3805
1. `@electron-forge/maker-wix` replaces **the version (semantic version)** with the windows compatible, _making it an invalid semantic version_, e.g. `1.2.3-beta` -> `1.2.3.0`
2. `electron-wix-msi` expects a semantic `version` as an input option and then separates it into 2 versions:
- `semanticVersion` - used as an actual app version, e.g. `1.2.3-beta`
- `windowsCompliantVersion` - used as an `.msi` version that follows the Windows version format and doesn't support semver, e.g. `1.2.3.0`
- See: https://github.com/electron-userland/electron-wix-msi/blob/3d476237f631380e2252027c4fde20eacccd438e/src/creator.ts#L204-L205
3. `StubExecutable` expects the app to be in `app-{semver}` folder and search to the latest semantic version
- If there …
=> fix(maker-wix): version with pre-release tag breaks app start

packages/api/cli/src/electron-forge-init.ts, packages/api/cli/src/electron-forge.ts, packages/api/cli/src/util/check-system.ts, packages/api/core/spec/slow/api.slow.spec.ts, packages/api/core/src/api/import.ts, packages/api/core/src/api/init.ts
ref https://github.com/electron/forge/issues/3638
Allows users to skip initializing a Git repository with the `--skip-git` flag. Applies to both `import` and `init` commands.
=> feat(cli): add `--skip-git` option

packages/api/cli/src/util/check-system.ts, packages/utils/core-utils/src/package-manager.ts
Fixes #3864 by @mato533
* Added `.trim()` to pnpm config get outputs:
* Modified the retrieval of `hoistPattern`, `publicHoistPattern`, and `nodeLinker` to use `.trim()` on the results of `spawnPackageManager`. This removes trailing newlines (`\n`) from the `pnpm config get` output, ensuring accurate string comparisons.
* Before: `"undefined\n" !== 'undefined'` caused the check to misinterpret unset values as custom configurations.
* After: `"undefined\n".trim()` becomes `"undefined"`, correctly triggering the node-linker check when hoist patterns are unset.
=> fix(core-utils): trim `spawnPackageManager` output

packages/api/cli/src/electron-forge-start.ts, packages/api/cli/src/electron-forge.ts
Fixes https://github.com/electron/forge/issues/3873.
In https://github.com/electron/forge/pull/3848, we upgraded the `commander` library from v4 to v11, which brought in half a decade's worth of updates.
This change required us to use the newer `passThroughOptions()` setting to pass args to `process.argv` instead of to the program itself. I had previously tested that this worked specifically with the following invocation:
```
yarn start -- --inspect-electron -- --arg1 --arg2
```
However, as reported in the aforementioned issue, this approach didn't work with `yarn start yarn start -- -- --arg1 --arg2` when attempting to pass in app args without passing any args to Forge.
By inspecting the value of `process.argv` at the top level of `electron-forge-start.ts`, I noticed that the `--` values …
=> fix(start): pass app args with correct amount of `--`

packages/api/cli/src/electron-forge-import.ts, packages/api/cli/src/electron-forge-init.ts
Follow-up to https://github.com/electron/forge/pull/3860
I am a silly goose and forgot to actually wire the CLI option up to the API layer.
=> fix(cli): correctly wire up `--skip-git` opt

packages/utils/core-utils/spec/package-manager.spec.ts, packages/utils/core-utils/src/package-manager.ts
Follow-up to https://github.com/electron/forge/pull/3822.
Subtle bug here where `findUp` returns the absolute path so we need to `path.basename` it to grab the correct package manager. Fixed the test which had bad arrangement code.
=> fix(core-utils): correctly fall back package manager lockfile

packages/api/core/spec/fast/find-template.spec.ts, packages/api/core/src/api/init-scripts/find-template.ts, packages/api/core/src/api/init.ts
A common issue for Electron Forge's init command is that our internal template search logic prioritizes globally installed templates over locally installed ones.
In practice, this means that if you installed `npm install -g create-electron-app` at some point (we used to recommend that in our docs a long time ago), you'll run into a bug where `init` fails because it tries to fetch the global module installed with an incompatible Forge version.
ref https://github.com/electron/forge/issues/3874
This PR addresses the issue by suffixing `(local module)` or `(global module)` to the end of the file and resolving the actual template module name.
```
✔ Resolving package manager: yarn
✔ Resolving template: webpack-typescript
› Using @electron-forge/template-webpack-typescript (local module)
```
=> feat(cli): show template sources when initializing

packages/api/cli/package.json, packages/api/cli/src/electron-forge.ts, packages/api/cli/src/util/check-system.ts
Fixes #3554
This PR introduces an early Node.js version check in the `electron-forge.ts` CLI entry point. This prevents syntax errors caused by unsupported Node versions and provides a clear error message to the user.
=> fix(cli): add descriptive error for unsupported node version

package.json, packages/api/core/package.json, packages/api/core/spec/fast/util/forge-config.spec.ts, packages/api/core/spec/fixture/dummy_default_cts_conf/forge.config.cts, packages/api/core/spec/fixture/dummy_default_cts_conf/package.json, packages/api/core/spec/fixture/dummy_default_mts_conf/forge.config.mts, packages/api/core/spec/fixture/dummy_default_mts_conf/package.json, packages/api/core/src/util/forge-config.ts, packages/plugin/webpack/spec/fixtures/apps/native-modules/package-lock.json, yarn.lock
Fixes https://github.com/electron/forge/issues/3872 Fixes https://github.com/electron/forge/issues/3676 Fixes https://github.com/electron/forge/issues/3609 Fixes https://github.com/electron/forge/issues/3780 Fixes https://github.com/electron/forge/issues/3671
Closes #3881
#3872 reported that TypeScript configurations stopped working in Node 23.6, which is the first version where [type stripping](https://nodejs.org/api/typescript.html#type-stripping) in Node.js is available unflagged.
Simply using a `forge.config.ts` file fails to load with Node v23.6 and above, which indicates some sort of failure in our existing TS config toolchain.
<details>
<summary><b>How does `forge.config.ts` get loaded?</b></summary>
#2993 added support for arbitrary non-JavaScript configuration files using Gulp's …
=> fix(core): load TypeScript configurations with `jiti`

.github/workflows/stale.yml
This action wasn't working because I had `only-labels` (AND) with two mutually exclusive labels. We instead want [`any-of-labels`](https://github.com/actions/stale?tab=readme-ov-file#any-of-labels), which is an OR operation.
=> ci(stale): use `any-of-labels`

yarn.lock
The lack of support for Electron 36 in the lockfile's `node-abi` file breaks our integration tests in CI, I believe.
I think this will get the pipeline back up. As an alternative, we should look into pinning the Electron version installed when we initialize a Forge app in testing so that we have a more reproducible environment.
=> build(deps): update node-abi to latest 3.x

packages/plugin/webpack/spec/WebpackConfig.spec.ts, packages/plugin/webpack/src/WebpackConfig.ts
There's was no need to omit the `index.html` in development mode in the first place, and it makes relative URL resolve differently than in production.
=> fix(plugin-webpack): make entry point consistent between dev and prod

yarn.lock
Closes https://github.com/electron/forge/issues/3447
As a drive-by upgrade, this standardizes the version of `@electron/asar` we use to a single one.
=> fix(package): update `@electron/universal` to v2.0.3

packages/api/core/src/api/init-scripts/init-link.ts, packages/plugin/fuses/spec/FusesPlugin.slow.spec.ts
Split off from https://github.com/electron/forge/pull/3881
Makes `FusesPlugin.slow.spec.ts` use the local build of Forge instead of the production version of Forge.
=> test(plugin-fuses): use local build for tests

packages/template/base/src/BaseTemplate.ts
Add `electron-winstaller` in `onlyBuiltDependencies` when using pnpm.
Related issue: https://github.com/electron/forge/issues/3892 https://github.com/electron/forge/issues/3900
There are also some issues related in **Squirrel.Windows**: https://github.com/Squirrel/Squirrel.Windows/issues/1715, indicating that the same error will occur when using Chinese characters in the path. Maybe we could also mention it in the doc?
=> fix: add electron-winstaller in onlyBuiltDependencies

packages/template/vite-typescript/tmpl/package.json, packages/template/webpack-typescript/tmpl/package.json
Remove ts-node as we don't need it
=> fix: remove unused `ts-node` in template

packages/api/core/src/api/package.ts
Takes function, wraps function, hides return value.
Get's rid of these deprecation warnings:
```
(node:7781) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
at node:internal/util:473:17
at new Promise (<anonymous>)
at AsyncFunction.<anonymous> (node:internal/util:458:12)
at /Users/.../app/node_modules/@electron/packager/dist/hooks.js:9:73
at Array.map (<anonymous>)
at promisifyHooks (/Users/.../app/node_modules/@electron/packager/dist/hooks.js:9:29)
at MacApp.copyTemplate (/Users/.../app/node_modules/@electron/packager/dist/platform.js:137:46)
at async MacApp.buildApp (/Users/.../app/node_modules/@electron/packager/dist/platform.js:125:9)
at async MacApp.initialize (/Users/.../app/node_modules/@electron/packager/dist/platform.js:120 …
```
=> fix: hide promises from promisify

package.json, packages/api/core/src/api/init-scripts/init-npm.ts, packages/plugin/fuses/package.json, yarn.lock
The `>=1.0.0` version range we had for the Fuses plugin broke installing the base template if you're on Node < 22.12 because we released a new SemVer major version that only supports Node 22.
=> fix(plugin-fuses): only use fuses v1

packages/plugin/vite/src/config/vite.main.config.ts, packages/plugin/vite/src/config/vite.preload.config.ts, packages/plugin/vite/src/config/vite.renderer.config.ts
Not sure if this should count as a breaking change, but the default setting should be to use `/public` for web/renderer content.
As it is, the public dir in Vite gets duplicated in the output build.
=> fix(plugin-vite): only copy `/public` in the renderer

vitest.workspace.mts
We get somewhat frequent flakes in the test due to the 120s timeout for slow tests since they might initialize and package a full app. Let's bump that up to try to fix that.
=> test: increase test timeout

yarn.lock
Follow-up to https://github.com/electron/forge/pull/3983
For some reason, `yarn install --frozen-lockfile` doesn't fail if there's just an entry to be removed and it just skips it instead.
This runs a clean `yarn install`.
=> chore: remove stale lockfile entry

packages/api/core/spec/fixture/async_forge_config/package.json, packages/api/core/spec/fixture/forge-config-no-package-json-config/package.json, socket.yml
Also ensures these package.json files can't be resolved / installed even if someone accidentally tries to
=> build: ignore fixture package.json in socket

packages/publisher/s3/spec/PublisherS3.spec.ts, packages/publisher/s3/src/Config.ts, packages/publisher/s3/src/PublisherS3.ts
AWS best practice for hosting content in S3 is to use a CloudFront distribution on top of the S3 bucket. When doing this, it's preferable to have an aggressive cache policy in place.
To ensure releases become available in a timely fashion, this change exposes a configuration item to set the Cache-Control max-age property against RELEASES files used by Electron's auto-update.
The change is backwards compatible and also introduces unit tests for the S3 publisher
=> feat: updated publisher-s3 to support cache max-age for release files

packages/api/cli/src/electron-forge-init.ts
Follow-up to https://github.com/electron/forge/commit/20823ab9768e25c83a602c4d20aa3aa24b406b6e
Trying to use the interactive mode in a folder that _doesn't_ already exist doesn't work, which is very unfortunate. 😅
=> fix(init): unbreak interactive force check
