electron/forge

- package.json
> fix(generic): fix package.json warning about repository

- .npmignore
- .travis.yml
- README.md
- ci/Dockerfile
- ci/docker.sh
- ci/script.sh
- package.json
- src/makers/linux/flatpak.js
Had to replace the normal Travis Linux worker with a Docker container, because the Flatpak PPA is busted on Ubuntu 14.04.
> feat(maker): add the flatpak maker for the linux target

- package.json
- src/electron-forge-package.js
:skull: `console.error` monkeypatching.
> refactor(packager): upgrade to Electron Packager 8.4.0 (with quiet option)

- package.json
- src/electron-forge-package.js
- src/util/compile-hook.js
ISSUES CLOSED: Fixes #7
/cc @malept
> refactor(packager): move packager compile logic to a electron-packager afterCopy hook

- README.md
Lots of wording/formatting changes.
> docs(generic): clean up README

- .travis.yml
**Have you read the [section in CONTRIBUTING.md about pull requests](https://github.com/MarshallOfSound/electron-forge/blob/master/CONTRIBUTING.md#filing-pull-requests)?**
Yes
N/A
N/A
N/A
We only need PR builds, not branches. `master` and release tags still get built.
> chore(tests): disable building branches on Travis CI

- ci/fix-changelog.js
- src/electron-forge-make.js
- src/electron-forge-package.js
- src/makers/darwin/dmg.js
- src/makers/generic/zip.js
- src/makers/linux/deb.js
- src/makers/linux/flatpak.js
- src/makers/linux/rpm.js
- src/makers/win32/squirrel.js
- src/util/electron-host-arch.js
- src/util/forge-config.js
*Insert meaningful PR body here*
> Multi arch make

- README.md
- package.json
- src/electron-forge.js
- src/util/check-system.js
Yes
Yes
Yes
Yes
I noticed this because of #16.
> fix(generic): document that the minimum Node version is 6

- src/electron-forge-start.js
- src/util/rebuild.js
- test/fixture/native_app/package.json
- test/rebuild_spec.js
Yes
N/A
Yes
Yes
Modify the rebuilder so it only rebuilds prod modules or modules that are deep children of prod modules.
Fixes #23.
> Better rebuild

- src/electron-forge-make.js
- src/electron-forge-package.js
- src/electron-forge-start.js
- src/init/init-npm.js
- src/util/compile-hook.js
- src/util/forge-config.js
- src/util/read-package-json.js
- src/util/rebuild.js
- src/util/resolve-dir.js
- test/cli_spec.js
Yes
N/A
Yes
Yes
This is an experiment to standardize reading/parsing `package.json` files.
> refactor(generic): standardize reading package.json files

- package.json
- src/electron-forge-init.js
- src/init/init-custom.js
- src/init/init-npm.js
- src/init/init-starter-files.js
- test/cli_spec.js
- test/fixture/custom_init/index.js
- test/fixture/custom_init/package.json
ISSUES CLOSED: #35
Yes
No
Init is still covered, custom templaters should test their own modules.
Yes
Add the ability to specify a `--template=[name]` option, for instance `--template=react` when initialising a new project.  These template modules are resolved globally from a `electron-forge-template-[name]` pattern.
> feat(initializer): allow custom initializers

- README.md
> docs(importer): mention import in the README

- package.json
- src/electron-forge.js
ISSUES CLOSED: #49
This is just super basic tab completion (just the top level commands).  It looks kind of like this
> feat(generic): add basic tab completion for top level commands

- src/api/package.js
- src/init/init-npm.js
Fixes #66
Yes
N/A
N/A (when I do a test blitz on error pathways this will be covered)
N/A
> fix(packager): throw errors on an uncompilable entrypoint

- src/api/import.js
- tmpl/package.json
Yes
N/A
N/A
Yes
During import set the `start`, `package` and `make` scripts to be forgy 👍 
/cc @paulcbetts
> Set up scripts during import

- gulpfile.babel.js
- src/electron-forge-make.js
Yes
N/A
N/A
Yes
> fix the forge alias so that it can run the make command
> fix(alias): fix the forge alias so that it can run the make command

- .eslintrc
- src/api/install.js
- src/api/lint.js
- src/api/make.js
- src/api/package.js
- src/api/publish.js
- src/api/start.js
- src/init/init-custom.js
- src/installers/darwin/zip.js
- src/util/resolve-dir.js
ISSUES CLOSED: #79
Yes
N/A
N/A
Yes
See #79
> chore(generic): disable the no-throw-literal eslint rule

- src/init/init-custom.js
Yes
N/A
Needs a test for nonexistent templates, but it should go into #85.
Yes
ISSUES CLOSED: #87
> fix(initializer): handle local templates correctly

- README.md
Yes
Yes
N/A
N/A
Mention some of the major packages that Forge depends on, in particular electron-rebuild. Thanks to @enlight for mentioning that it should probably be documented.
> docs(generic): clarify what the major package dependencies are

- package.json
Yes
N/A
N/A
Yes
Update dmg dependency to get the "compress" feature 👍
> chore(generic): update electron-installer-dmg to version 0.2.0

- package.json
- tabtab-install.js
ISSUES CLOSED: #98
Yes
N/A
N/A
Yes
Read commit 👍
> fix(tabtab): dont install tabtab in a development environment and ignore tabtab install errors

- src/publishers/github.js
- src/util/github.js
- test/fast/github_spec.js
Yes
N/A
Yes
Yes
Based on a problem someone had in the Atom #electron Slack channel.
> fix(publisher): throw an exception if a GitHub token isn't specified

- src/util/hdiutil.js
Yes
Yes
Yes
Yes
Fix a typo from `iamgePath` to `imagePath`
> style(util): fix typo re: imagePath

- src/api/package.js
- test/slow/api_spec_slow.js
ISSUES CLOSED: #133
Yes
N/A
Yes
Yes
See issue
> feat(packager): remove the users forge config after packaging for safety reasons

- src/publishers/s3.js
> fix(publisher): Fix secret access key

- src/api/make.js
- src/api/publish.js
> feat(generic): allow third party modules to be named whatever they want

- src/makers/darwin/dmg.js
- src/makers/linux/deb.js
- src/makers/linux/flatpak.js
- src/makers/linux/rpm.js
- src/makers/win32/appx.js
- src/makers/win32/squirrel.js
- src/util/config-fn.js
> feat(maker): allow maker configs to be functions that return values based on arch

- src/init/init-npm.js
> fix(initializer): fix linting install for airbnb style

- src/makers/linux/deb.js
- src/makers/linux/rpm.js
> fix(maker): handle name option for the deb, rpm makers as well as dmg

- test/slow/api_spec_slow.js
Using flatpak with Docker no longer seems to work and makes it difficult to find other test failures.
I'm going to figure out how to fix the flatpak tests in a separate branch.
> fix(tests): disable flatpak tests

- src/makers/win32/appx.js
> fix(maker): dont throw makeappx location errors if the user provided a path

- .travis.yml
- ci/script.sh
> fix(ci): install older version of yarn on travis

- package.json
- src/util/rebuild.js
Use the new electron-rebuild 1.6.0 option-based API to avoid the deprecation warning.
> refactor(generic): use the options-based electron-rebuild API

- src/util/check-system.js
The version whitelists need to be updated and audited.
Fixes #269.
> feat(generic): print a warning if the package manager used is not a known good version

- src/api/make.js
- test/slow/api_spec_slow.js
ISSUES CLOSED: #227
Sww #227 for the error this fixes 👍
> fix(maker): allow comma separated arches in make as well as package

- README.md
- src/init/init-npm.js
- test/slow/api_spec_slow.js
Fixes #294.
Also adds docs to show alternate methods of creating apps with Forge (namely, `npx` and `yarn create`).
> init should install Forge locally

- README.md
* <del>The changes have sufficient test coverage</del> (not applicable).
* <del>The testsuite passes successfully on my local machine</del> (not applicable).*
Fixes https://github.com/electron-userland/electron-forge/pull/126#discussion_r133446820
> docs(publisher): fix S3 config key typo

- package.json
- src/api/package.js
I just released Electron Packager 9 :tada:
We might have to major version bump Forge due to all of the breaking changes. _(In that case, there's some FIXMEs about dropping things in the event of a major version bump that we should deal with.)_
> chore(generic): upgrade Electron Packager to 9.x

- README.md
- src/api/init.js
- src/electron-forge-init.js
- src/init/init-starter-files.js
- test/slow/api_spec_slow.js
- tmpl/_appveyor.yml
- tmpl/_travis.yml
- tmpl/package.json
> BREAKING CHANGE: feat(initializer): add Travis/AppVeyor CI files to default template

- src/util/check-system.js
Being super-optimistic here, but that's what we're installing in Travis now.
> fix(generic): whitelist yarn >= 1.0.0

- README.md
* ~~The changes have sufficient test coverage~~ (not applicable).
* ~~The testsuite passes successfully on my local machine~~ (not applicable).
ISSUES CLOSED: #318
> docs(maker): mention that make can support non-host platforms

- src/util/check-system.js
See: https://github.com/npm/npm/issues/17671
> fix(generic): blacklist NPM 5.4.[01] on Windows

- src/util/check-system.js
- test/fast/system_spec.js
> fix(generic): automatically warn w/a nightly package manager version

- src/api/make.js
- src/makers/generic/zip.js
- test/slow/api_spec_slow.js
Well mas didn't work and now it does 👍
> Allow building for MAS inside make logic

- src/api/import.js
- src/init/init-npm.js
- src/util/forge-config.js
> fix(importer): adjust Forge config defaults just like in init

- README.md
> docs(starter): add note to readme about debugging on the command line

- ci/script.sh
- package.json
- src/makers/linux/flatpak.js
- test/fast/makers/flatpak_spec.js
- test/slow/api_spec_slow.js
* re-enables the flatpak tests (now that it seems that running Docker in privileged mode works on Travis)
* upgrades `electron-installer-flatpak` to 0.8.0
* fixes the flatpak artifact detection (because the module docs were inaccurate, which I fixed in https://github.com/endlessm/electron-installer-flatpak/pull/18)
> Upgrade to electron-installer-flatpak 0.8.0

- src/api/package.js
> fix(packager): packager hooks should be executed sequentially

- README.md
- src/api/package.js
- src/api/start.js
- src/util/forge-config.js
- src/util/rebuild.js
- test/fast/forge-config_spec.js
- test/slow/rebuild_spec_slow.js
Put an electronRebuildConfig in the forge config and pass it through to electron-rebuild.
> feat(rebuilder): allow configuration of electron-rebuild

- CONTRIBUTING.md
- README.md
- SUPPORT.md
Adds a support doc with more possible values for `DEBUG`, and a table of contents for the README.
> Add SUPPORT

- .appveyor.yml
- README.md
- package.json
- src/makers/win32/appx.js
- src/makers/win32/wix.js
- src/util/author-name.js
- test/fast/author-name_spec.js
- test/fast/makers/appx_spec.js
> Add Electron Wix MSI support

- README.md
Also add some quick instructions on how to use.
Per https://github.com/electron-userland/electron-forge/pull/427#issuecomment-362142438
> Add links to third-party makers/publishers on NPM

- .appveyor.yml
- .travis.yml
- src/publishers/electron-release-server.js
This is a backport of #465 to the 5.x series.
> fix(publisher): call resolve() when electron-release-server publisher succeeds (5.x)

- package.json
- packages/api/core/package.json
- packages/api/core/src/api/package.js
- packages/api/core/src/util/forge-config.js
- packages/api/core/test/slow/api_spec_slow.js
- yarn.lock
RIP `packageManager`.
Moved the rebuild hook to always go into `afterCopy` since prune happens at copy time now.
> chore(generic): upgrade to Electron Packager 12

- README.md
- src/api/package.js
- test/slow/api_spec_slow.js
A forward-port for 6.x is forthcoming.
ISSUES CLOSED: #508
> fix(packager): disable the all option (5.x)

- .editorconfig
`*.ts` was missing from `.editorconfig` so I added it.
> chore(core): add *.ts to .editorconfig

- .travis.yml
Bumping bolt version in Travis to prevent the annoying log prefix in logs.
> bumps bolt version in Travis (was already bumped in docker and appveyor

- package.json
> [5.x] chore(maker): upgrade electron-wix-msi to 2.x

- packages/maker/dmg/package.json
- packages/maker/dmg/src/MakerDMG.ts
- packages/maker/dmg/test/MakerDMG_spec.ts
> fix(maker-dmg): return correct path from dmg maker

- package.json
- packages/api/core/test/slow/api_spec_slow.ts
- packages/maker/deb/package.json
- packages/maker/rpm/package.json
- packages/maker/rpm/src/MakerRpm.ts
- packages/maker/rpm/test/MakerRpm_spec.ts
- packages/maker/snap/package.json
- packages/publisher/snapcraft/package.json
- yarn.lock
Same as #659 except we're actually bumping `-redhat`. [Release notes](https://github.com/electron-userland/electron-installer-redhat/releases/tag/v1.0.0)
Addresses #654.
> [6.x] chore(maker): update debian/redhat/snap installer dependencies

- package.json
- packages/api/core/src/util/publish-state.ts
- packages/plugin/webpack/src/WebpackPlugin.ts
- yarn.lock
This is my attempt at upgrading Typescript. At minimum, it fixes the build errors, but perhaps not in the optimal way.
> chore: upgrade typescript to 3.2.2

- package.json
- packages/api/core/test/slow/api_spec_slow.ts
- packages/maker/squirrel/package.json
- yarn.lock
Fixes Windows CI 👍 
* ps1 issue from either bolt or yarn, not sure which
* update `electron-winstaller` dep
> Fix Windows CI

- ci/docker.sh
- package.json
- packages/maker/flatpak/package.json
- packages/maker/flatpak/src/MakerFlatpak.ts
- packages/maker/flatpak/test/MakerFlatpak_spec.ts
- yarn.lock
Upgrades dependencies (like `asar@^1.0.0`), uses Promises, and other enhancements.
> chore: switch flatpak maker to @malept/electron-installer-flatpak

- packages/plugin/webpack/src/WebpackPlugin.ts
> refactor (plugin-webpack): extract methods from getDefines

- package.json
- packages/api/cli/package.json
- packages/api/core/package.json
- yarn.lock
Upgrades the dependencies that dependabot can't handle (because bolt).
> chore: upgrade dependencies

- packages/utils/web-multi-logger/package.json
The `package.json description` was the wrong copypasta. Instead, copied the summary from its README.
> chore(web-multi-logger): fix package description

- package.json
- packages/api/core/package.json
- packages/utils/types/package.json
- yarn.lock
The most notable thing is the `node-gyp` upgrade.
> chore: upgrade electron-rebuild to ^1.8.5

- package.json
- packages/maker/dmg/package.json
- packages/maker/dmg/src/MakerDMG.ts
- packages/maker/dmg/test/MakerDMG_spec.ts
- yarn.lock
> chore: upgrade electron-installer-dmg to ^3.0.0

- README.md
Fixed plugins link in README.md
> docs: fix plugins link

- package.json
- packages/api/core/package.json
- packages/api/core/src/util/electron-version.ts
- packages/api/core/test/fast/electron-version_spec.ts
- packages/api/core/test/fixture/yarn-workspace/node_modules/electron/package.json
- yarn.lock
> fix: search for the top-level node_modules folder when using yarn workspaces

- package.json
- packages/maker/deb/package.json
- packages/maker/deb/src/MakerDeb.ts
- packages/maker/deb/test/MakerDeb_spec.ts
- packages/maker/rpm/package.json
- packages/maker/rpm/src/MakerRpm.ts
- packages/maker/rpm/test/MakerRpm_spec.ts
- yarn.lock
Node 8 syntax + Electron 5 compatibility.
> chore: upgrade electron-installer-{debian,redhat} to ^2.0.0

- SUPPORT.md
- package.json
- packages/api/core/package.json
- packages/api/core/src/api/import.ts
- packages/api/core/src/api/make.ts
- packages/api/core/src/api/package.ts
- yarn.lock
Getting Forge on board the `@electron/get` train :steam_locomotive: 
Depends on https://github.com/electron/get/pull/94.
> refactor: convert from electron-download to @electron/get

- package.json
- packages/maker/flatpak/package.json
- yarn.lock
Actually works with modern Electron versions!
[Release Notes](https://github.com/malept/electron-installer-flatpak/releases/tag/v0.10.0)
> chore: upgrade @malept/electron-installer-flatpak to ^0.10.0

- package.json
- packages/api/core/package.json
- packages/api/core/src/util/parse-archs.ts
- packages/maker/snap/package.json
- packages/publisher/snapcraft/package.json
- yarn.lock
New major versions of both were released this morning.
> chore: upgrade to Electron Packager 14 & electron-installer-snap 4

- packages/api/core/tmpl/_appveyor.yml
- packages/api/core/tmpl/_travis.yml
Modernize the Travis CI config template and update both CI config templates to Node 8.
> fix(core): update CI templates to Node 8 and other updates

- package.json
- packages/utils/types/package.json
- yarn.lock
Preemptively do it before dependabot gets to it.
> chore: upgrade @types/electron-packager to ^14.0.0

- yarn.lock
Preemptively making a PR before dependabot.
> chore: upgrade Electron Packager to 14.0.1

- CONTRIBUTING.md
- tools/bump.js
Fixed a long-standing release bug that annoyed me :smile:
Works around the lack of a feature in `generate-changelog` (manually specifying a version).
> chore: make sure the changelog modifications are with the proper git tag

- .travis.yml
Per https://github.com/electron-userland/electron-forge/pull/1052#issuecomment-515156032
> build: use Node 12 for the docs stage on Travis CI

- package.json
- packages/api/core/package.json
- packages/api/core/src/util/install-dependencies.ts
- yarn.lock
There is a regression in `yarn-or-npm` 3.0.0, see #1098 and https://github.com/camacho/yarn-or-npm/pull/7
This also fixes a bug in the exception handler for install-dependencies, surfaced by the bug.
> Downgrade to yarn-or-npm 2

- package.json
- packages/api/core/package.json
- yarn.lock
`yarn-or-npm` 3.0.1 has the fix I mentioned in #1102, so re-upgrade.
> chore(deps): upgrade yarn-or-npm to ^3.0.1

- .github/workflows/dependabolt.yml
Automates upgrading dependencies in bolt packages. (Dependabolt = Dependabot + Bolt :grin:)
Example action: https://github.com/malept/electron-forge/runs/209394870
Example commit generated and pushed: https://github.com/electron-userland/electron-forge/commit/1af9f10a5e643c7d62d570837b564cff684a9363
> chore: add dependabolt GitHub Action workflow

- packages/api/core/test/slow/api_spec_slow.ts
- packages/template/typescript/tmpl/index.ts
- packages/template/typescript/tmpl/tslint.json
Make sure the TypeScript template actually passes `tslint`.
> test(template-typescript): run lint for template & adjust default rules

- packages/api/core/src/util/config-fn.ts
I can't find any code in the repo that actually uses this.
> refactor(core): remove unused config-fn utility file

- packages/template/base/tmpl/index.js
- packages/template/typescript-webpack/tmpl/index.ts
- packages/template/typescript/test/TypeScriptTemplate_spec.ts
- packages/template/typescript/tmpl/index.ts
See: https://github.com/electron/electron/pull/21957 and https://github.com/electron/fiddle/pull/312
> fix(template): stop holding a reference to mainWindow

- package.json
- yarn.lock
Also groups the package-specific config to the end of `package.json`.
Closes #1340.
> chore: changes to TypeScript files have eslint --fix run on them

- .github/dependabot.yml
Adds support for GitHub Dependabot (v2) plus updating supported GitHub Actions.
> build: add Dependabot config

- packages/api/core/src/api/init-scripts/init-npm.ts
> fix(core): init should install the latest caret version of Forge

- package.json
- packages/publisher/github/src/util/github.ts
- tools/update-dependencies.js
- yarn.lock
Upgrades almost every dependency and adds a script to batch update dependencies in the event that we're super behind in Dependabot PRs.
> build: add script to batch update dependencies

- .github/workflows/ci.yml
Moves the Dependabolt Docker container from Docker Hub to GitHub Container Registry.
> ci: use dependabolt v2.1.3

- packages/utils/async-ora/src/ora.ts
Clarify how to view progress indicators when `DEBUG` is set.
> docs(async-ora): clarify use with DEBUG

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/ci.yml
- CONTRIBUTING.md
- packages/api/core/test/slow/api_spec_slow.ts
Uses the [`fastify/github-action-merge-dependabot`](https://github.com/fastify/github-action-merge-dependabot) action to auto-merge dependency updates from Dependabot that pass all tests.
Also updates the Electron CoC links (`master` :arrow_right: `main`).
> ci: automerge Dependabot PRs

- packages/plugin/webpack/test/fixtures/apps/native-modules/package.json
- packages/template/typescript-webpack/tmpl/package.json
- packages/template/webpack/tmpl/package.json
Does what it says on the tin. This is done outside of dependabot since it needs to be tested first.
> chore(deps): upgrade @vercel/webpack-asset-relocator-loader to 1.6.0

- .github/workflows/ci.yml
* use the built-in caching feature from `actions/setup-node`
* Simplify WiX configuration
> ci: simplify

- packages/template/typescript-webpack/src/TypeScriptWebpackTemplate.ts
Fixes https://github.com/electron-forge/electron-forge-docs/issues/41
> fix(template-typescript-webpack): lint tsx files by default

- package.json
- packages/api/core/package.json
- packages/api/core/src/util/rebuild.ts
- packages/api/core/test/slow/api_spec_slow.ts
- packages/utils/types/package.json
- packages/utils/types/src/index.ts
- yarn.lock
See https://github.com/electron/electron-rebuild/releases/tag/v3.0.0 and https://github.com/electron/electron-rebuild/releases/tag/v3.1.0
> feat(deps): upgrade to electron-rebuild@^3.1.1

- .babelrc
Missed this when the minimum Node.js version was updated.
> build(babel): target Node 12

- .github/ISSUE_TEMPLATE/config.yml
- SUPPORT.md
Links that doesn't be updated in 0a71bc6508583370a4ced3a8343d7e13f0cf4b3a
> docs: update discord invite

- packages/template/typescript-webpack/tmpl/renderer.ts
- Update the documentation related to main/renderer contexts to the correct link.
> chore(template-typescript-webpack): update broken docs link

- codecov.yml
Attempt to set up https://docs.codecov.com/docs/commit-status#threshold
> chore: add threshold to codecov

- .github/workflows/gh-pages.yml
- package.json
See output: https://github.com/electron-userland/electron-forge/tree/gh-pages
> build: add Action for GitHub Pages deploy

- package.json
- packages/maker/dmg/package.json
- yarn.lock
> chore(maker-dmg): upgrade electron-installer-dmg to 4.0.0

- .github/workflows/gh-pages.yml
> build: don't run GH Pages on PR

- package.json
- tools/gen-docs.ts
- yarn.lock
As in title, the plugin does it all for us.
> docs: ensure referenced types are included in typedoc site

- yarn.lock
gets rid of a warning message at least
> build(deps): npx browserslist@latest --update-db

- tools/gen-docs.ts
> chore: rename <Internal> to InternalModule

- package.json
- packages/maker/wix/package.json
- yarn.lock
> build: upgrade electron-wix-msi to 4.0.0

- package.json
- yarn.lock
> build: fix some yarn audit output

- packages/template/typescript-webpack/src/TypeScriptWebpackTemplate.ts
> fix(template-typescript-webpack): clean up forge config code

- packages/api/core/test/fast/resolve-dir_spec.ts
- packages/api/core/test/fixture/forge-config-no-package-json-config/forge.config.js
- packages/api/core/test/fixture/forge-config-no-package-json-config/package.json
Small PR, adding a test for the future to detect any forge.config detection issues
Should prevent issues like #3028
> test: add test to detect forge.config

- packages/api/core/src/util/forge-config.ts
> fix: do not proxify class instances in forge config

- package.json
- packages/api/core/package.json
- packages/plugin/webpack/package.json
- packages/utils/types/package.json
- yarn.lock
Bumps electron-packager to 17.1.1
> chore: bump packager to 17.1.1

- tools/publish.js
Changes back the isBeta() value prior to stable!
> build: change isBeta back to beta value

- CONTRIBUTING.md
> docs: correct command

- package.json
> build: add preversion to scripts

- package.json
> build: add test flag to link Forge commands after running init

- CONTRIBUTING.md
> docs: remove mentions of lerna run test in contributing.md

- .husky/pre-push
- .husky/pre-push.js
- package.json
- yarn.lock
This PR adds a pre-push hook to provide a warning if the user attempts to push to main
> chore: add husky pre-push script

- .gitattributes
Prevents Git from converting LF to CRLF on checkout in case someone has `core.autocrlf` set to `true` (as I did).
> chore: add `.gitattributes` file for proper handling of line endings

- packages/utils/core-utils/package.json
Follow-up to grab one more missed in #3010.
> chore: update repo link from userland migration

- .github/workflows/ci.yml
Run CI in the merge queue so it provides meaningful value.
> ci: run tests in merge queue

- packages/publisher/github/README.md
There was an extra set of backticks in the Markdown.
> docs(publisher-github): clean up extra backticks

- packages/publisher/github/src/PublisherGithub.ts
Simplifying some code by using `Array.flatmap`.
> refactor(publisher-github): use Array.flatMap

- packages/plugin/vite/src/VitePlugin.ts
> fix(plugin-vite): right time to start

- packages/plugin/vite/src/VitePlugin.ts
process exit on electron process exit
> fix(vite-plugin): process exit on electron process exit

- README.md
> docs: update README status badge

- package.json
- packages/maker/deb/package.json
- yarn.lock
> build(deps): update `electron-installer-debian` to latest

- packages/api/cli/src/electron-forge.ts
Uhhhh we don't have `lint` or `install` anymore as of some betas ago.
> fix(cli): update `--help` command output

- .github/workflows/add-to-project.yml
Updates this workflow and uses the new actions over at `dsanders11/project-actions` which simplify the workflow a little.
> ci: update add to project workflow

- packages/api/cli/src/util/check-system.ts
> fix: re-allow Yarn 2 and above

- .github/workflows/gh-pages.yml
> build(docs): enable API documentation builds for Forge v7

- README.md
> docs: remove mention of v5 -> v6 migration

- package.json
- packages/api/core/package.json
- packages/api/core/src/api/package.ts
- packages/api/core/src/util/parse-archs.ts
- packages/plugin/webpack/package.json
- packages/utils/types/package.json
- yarn.lock
This PR updates Packager to the first version that includes the Typescript rewrite (https://github.com/electron/packager/pull/1593) to ensure Forge will work with future Packager versions, since a few types have been moved around.
> chore: update Packager

- package.json
- packages/api/core/package.json
- packages/plugin/vite/package.json
- packages/plugin/webpack/package.json
- packages/utils/types/package.json
- yarn.lock
fix: Bump `@electron/packager` to ^18.3.5, ensuring that `@electron/packager` correctly imports `@electron/asar`.
> fix: Bump @electron/packager to ^18.3.5

- packages/plugin/webpack/src/WebpackPlugin.ts
> feat(plugin-webpack): support for dev server custom headers

- yarn.lock
Fixes a few things in https://github.com/electron/forge/security/dependabot
> build(deps): upgrade lockfile deps for audit

- yarn.lock
Fixes another Dependabot warning for Lodash.
> build(deps): upgrade electron-winstaller

- packages/plugin/vite/package.json
> build(plugin-vite): add declare file to npm

- package.json
- yarn.lock
> build(deps): remove unused `pretty-ms` dep

- yarn.lock
This became out-of-date and needs to be updated.
> build: update outdated yarn.lock

- yarn.lock
* `npx uuaw express`
* `npx uuaw nanoid`
* `npx uuaw vite`
> build(deps): bump deps to partially clear audit

- packages/template/vite-typescript/src/ViteTypeScriptTemplate.ts
Like https://github.com/electron/forge/pull/3825, but for the TS template.
Closes https://github.com/electron/forge/issues/3768
> fix(template-vite-typescript): make `--force` flag work

- packages/api/core/spec/slow/api.slow.spec.ts
- yarn.lock
Closes https://github.com/electron/forge/issues/2871
Closes https://github.com/electron/forge/issues/3147
> test: unskip prebuilt-native-module test

- packages/utils/core-utils/spec/package-manager.spec.ts
Fast follow-up to #3866 which adds some test coverage. 🙂
> test(core-utils): add test coverage for spawnPackageManager

- packages/api/core/spec/slow/api.slow.spec.ts
This PR updates references to `electron-quick-start` to the renamed repo `minimal-repro`
> chore: update electron-quick-start references

- yarn.lock
> build(deps): update `form-data`

- README.md
- packages/external/create-electron-app/README.md
Aligns us with the actual docs.
ref https://github.com/electron/forge/issues/3970
> docs: update README install instructions
